// Code generated by services/dsh/tools/generate-types.mjs; DO NOT EDIT.
// Source: services/dsh/contracts/openapi/dsh.openapi.yaml and referenced path modules.
// Source Graph SHA: 41926eb72590792b469e3d0e433d428fe0d071d1

package contract

import "time"

type StatusResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type CreateJoiningCaseRequest struct {
	ContactPhoneE164 string `json:"contactPhoneE164"`
	BusinessName     string `json:"businessName"`
	FirstStoreName   string `json:"firstStoreName"`
}

type JoiningCaseState string

type JoiningCaseView struct {
	ID               string           `json:"id"`
	ContactPhoneE164 string           `json:"contactPhoneE164"`
	BusinessName     string           `json:"businessName"`
	FirstStoreName   string           `json:"firstStoreName"`
	PartnerActorID   string           `json:"partnerActorId,omitempty"`
	State            JoiningCaseState `json:"state"`
	CorrectionReason string           `json:"correctionReason,omitempty"`
	ReviewedBy       string           `json:"reviewedBy,omitempty"`
	Store            *StoreView       `json:"store,omitempty"`
	Version          int              `json:"version"`
	CreatedAt        time.Time        `json:"createdAt"`
	UpdatedAt        time.Time        `json:"updatedAt"`
}

type JoiningCaseResponse struct {
	Case             JoiningCaseView `json:"case"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type JoiningCaseSummary struct {
	ID               string           `json:"id"`
	ContactPhoneE164 string           `json:"contactPhoneE164"`
	BusinessName     string           `json:"businessName"`
	FirstStoreName   string           `json:"firstStoreName"`
	PartnerActorID   string           `json:"partnerActorId,omitempty"`
	State            JoiningCaseState `json:"state"`
	CorrectionReason string           `json:"correctionReason,omitempty"`
	ReviewedBy       string           `json:"reviewedBy,omitempty"`
	Version          int              `json:"version"`
	CreatedAt        time.Time        `json:"createdAt"`
	UpdatedAt        time.Time        `json:"updatedAt"`
}

type JoiningCaseListResponse struct {
	Cases      []JoiningCaseSummary `json:"cases"`
	NextCursor string               `json:"nextCursor,omitempty"`
}

type CorrectJoiningCaseRequest struct {
	BusinessName   string `json:"businessName"`
	FirstStoreName string `json:"firstStoreName"`
}

type ReviewJoiningCaseRequest struct {
	Decision         string `json:"decision"`
	CorrectionReason string `json:"correctionReason,omitempty"`
}

type StorePublicationReadiness struct {
	Ready         bool   `json:"ready"`
	BlockedReason string `json:"blockedReason,omitempty"`
}

type StoreView struct {
	ID                   string                    `json:"id"`
	PartnerActorID       string                    `json:"partnerActorId"`
	Name                 string                    `json:"name"`
	Version              int                       `json:"version"`
	PublicationState     PublicationState          `json:"publicationState"`
	PublicationReadiness StorePublicationReadiness `json:"publicationReadiness"`
	PublicationChangedAt *time.Time                `json:"publicationChangedAt,omitempty"`
	Assortments          []StoreAssortment         `json:"assortments"`
	CreatedAt            time.Time                 `json:"createdAt"`
	UpdatedAt            time.Time                 `json:"updatedAt"`
}

type PublicationState string

type PublicationAction string

type StorePublicationRequest struct {
	State PublicationAction `json:"state"`
}

type StorePublicationResponse struct {
	Store            StoreView `json:"store"`
	IdempotentReplay bool      `json:"idempotentReplay"`
}

type DeliveryOrigin struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type DeliveryAddress struct {
	ID          string    `json:"id"`
	AddressText string    `json:"addressText"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
	Version     int       `json:"version"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type CreateDeliveryAddressRequest struct {
	AddressText string  `json:"addressText"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

type UpdateDeliveryAddressRequest struct {
	AddressText string  `json:"addressText"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

type DeliveryAddressResponse struct {
	Address          DeliveryAddress `json:"address"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type DeliveryAddressListResponse struct {
	Addresses  []DeliveryAddress `json:"addresses"`
	NextCursor string            `json:"nextCursor"`
}

type SetStoreDeliveryOriginRequest struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type StoreDeliveryOriginResponse struct {
	StoreID          string          `json:"storeId"`
	OriginVersion    int             `json:"originVersion"`
	Origin           *DeliveryOrigin `json:"origin"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type SellUnit string

type CentralProduct struct {
	ID                string    `json:"id"`
	CanonicalName     string    `json:"canonicalName"`
	Brand             string    `json:"brand,omitempty"`
	Barcode           string    `json:"barcode,omitempty"`
	CanonicalImageUrl string    `json:"canonicalImageUrl,omitempty"`
	SellUnit          SellUnit  `json:"sellUnit"`
	Active            bool      `json:"active"`
	Version           int       `json:"version"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type CreateCentralProductRequest struct {
	CanonicalName     string   `json:"canonicalName"`
	Brand             string   `json:"brand,omitempty"`
	Barcode           string   `json:"barcode,omitempty"`
	CanonicalImageUrl string   `json:"canonicalImageUrl,omitempty"`
	SellUnit          SellUnit `json:"sellUnit"`
}

type UpdateCentralProductRequest struct {
	CanonicalName     string `json:"canonicalName"`
	Brand             string `json:"brand,omitempty"`
	Barcode           string `json:"barcode,omitempty"`
	CanonicalImageUrl string `json:"canonicalImageUrl,omitempty"`
	Active            bool   `json:"active"`
}

type CentralProductResponse struct {
	Product          CentralProduct `json:"product"`
	IdempotentReplay bool           `json:"idempotentReplay"`
}

type CentralProductListResponse struct {
	Products []CentralProduct `json:"products"`
}

type AssortmentPublicationState string

type StoreAssortment struct {
	StoreID           string                     `json:"storeId"`
	ProductID         string                     `json:"productId"`
	CanonicalName     string                     `json:"canonicalName"`
	Brand             string                     `json:"brand,omitempty"`
	Barcode           string                     `json:"barcode,omitempty"`
	CanonicalImageUrl string                     `json:"canonicalImageUrl,omitempty"`
	SellUnit          SellUnit                   `json:"sellUnit"`
	ProductActive     bool                       `json:"productActive"`
	ProductVersion    int                        `json:"productVersion"`
	PriceMinor        int                        `json:"priceMinor"`
	Currency          string                     `json:"currency"`
	Availability      bool                       `json:"availability"`
	PublicationState  AssortmentPublicationState `json:"publicationState"`
	Version           int                        `json:"version"`
	CreatedAt         time.Time                  `json:"createdAt"`
	UpdatedAt         time.Time                  `json:"updatedAt"`
}

type CreateStoreAssortmentRequest struct {
	ProductID  string `json:"productId"`
	PriceMinor int    `json:"priceMinor"`
}

type UpdateStoreAssortmentRequest struct {
	PriceMinor       int                        `json:"priceMinor"`
	Availability     bool                       `json:"availability"`
	PublicationState AssortmentPublicationState `json:"publicationState"`
}

type StoreAssortmentResponse struct {
	Assortment       StoreAssortment `json:"assortment"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type StoreAssortmentListResponse struct {
	Assortments []StoreAssortment `json:"assortments"`
}

type PublicStoreView struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Version     int               `json:"version"`
	Assortments []StoreAssortment `json:"assortments"`
	PublishedAt time.Time         `json:"publishedAt"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type PublishedStoreListResponse struct {
	Stores []PublicStoreView `json:"stores"`
}

type ErrorResponse struct {
	Error map[string]any `json:"error"`
}
