// Code generated by services/dsh/tools/generate-types.mjs; DO NOT EDIT.
// Source: services/dsh/contracts/openapi/dsh.openapi.yaml and referenced path modules.
// Source Graph SHA: dd67139b54a2a10125de768d83104505b19ccb59

package contract

import "time"

type StatusResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type ManagedRole string

type ProvisionManagedRoleRequest struct {
	PhoneE164 string      `json:"phoneE164"`
	Role      ManagedRole `json:"role"`
}

type SetManagedRoleStateRequest struct {
	PhoneE164 string      `json:"phoneE164"`
	Role      ManagedRole `json:"role"`
	Reason    string      `json:"reason"`
}

type PhoneReenrollmentRequest struct {
	PhoneE164 string      `json:"phoneE164"`
	Role      ManagedRole `json:"role"`
}

type CreateJoiningCaseRequest struct {
	ContactPhoneE164 string `json:"contactPhoneE164"`
	BusinessName     string `json:"businessName"`
	FirstStoreName   string `json:"firstStoreName"`
}

type JoiningCaseState string

type JoiningCaseView struct {
	ID               string           `json:"id"`
	ContactPhoneE164 string           `json:"contactPhoneE164"`
	BusinessName     string           `json:"businessName"`
	FirstStoreName   string           `json:"firstStoreName"`
	PartnerActorID   string           `json:"partnerActorId,omitempty"`
	State            JoiningCaseState `json:"state"`
	CorrectionReason string           `json:"correctionReason,omitempty"`
	ReviewedBy       string           `json:"reviewedBy,omitempty"`
	Store            *StoreView       `json:"store,omitempty"`
	Version          int              `json:"version"`
	CreatedAt        time.Time        `json:"createdAt"`
	UpdatedAt        time.Time        `json:"updatedAt"`
}

type JoiningCaseResponse struct {
	Case             JoiningCaseView `json:"case"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type ReviewJoiningCaseRequest struct {
	Decision         string `json:"decision"`
	CorrectionReason string `json:"correctionReason,omitempty"`
}

type StorePublicationReadiness struct {
	Ready         bool   `json:"ready"`
	BlockedReason string `json:"blockedReason,omitempty"`
}

type StoreView struct {
	ID                   string                    `json:"id"`
	PartnerActorID       string                    `json:"partnerActorId"`
	Name                 string                    `json:"name"`
	Version              int                       `json:"version"`
	PublicationState     PublicationState          `json:"publicationState"`
	PublicationReadiness StorePublicationReadiness `json:"publicationReadiness"`
	PublicationChangedAt *time.Time                `json:"publicationChangedAt,omitempty"`
	Items                []CatalogItem             `json:"items"`
	CreatedAt            time.Time                 `json:"createdAt"`
	UpdatedAt            time.Time                 `json:"updatedAt"`
}

type PublicationState string

type PublicationAction string

type StorePublicationRequest struct {
	State PublicationAction `json:"state"`
}

type StorePublicationResponse struct {
	Store            StoreView `json:"store"`
	IdempotentReplay bool      `json:"idempotentReplay"`
}

type CatalogPublicationState string

type CatalogItem struct {
	ItemID           string                  `json:"itemId"`
	StoreID          string                  `json:"storeId"`
	Name             string                  `json:"name"`
	PublicationState CatalogPublicationState `json:"publicationState"`
	Availability     bool                    `json:"availability"`
	Version          int                     `json:"version"`
	CreatedAt        time.Time               `json:"createdAt"`
	UpdatedAt        time.Time               `json:"updatedAt"`
}

type CreateCatalogItemRequest struct {
	Name string `json:"name"`
}

type UpdateCatalogItemRequest struct {
	Name             string                  `json:"name"`
	PublicationState CatalogPublicationState `json:"publicationState"`
	Availability     bool                    `json:"availability"`
}

type CatalogItemResponse struct {
	Item             CatalogItem `json:"item"`
	IdempotentReplay bool        `json:"idempotentReplay"`
}

type CatalogItemListResponse struct {
	Items []CatalogItem `json:"items"`
}

type PublicStoreView struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Version     int           `json:"version"`
	Items       []CatalogItem `json:"items"`
	PublishedAt time.Time     `json:"publishedAt"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type PublishedStoreListResponse struct {
	Stores []PublicStoreView `json:"stores"`
}

type ActorRoleView struct {
	ActorID           string     `json:"actorId"`
	PhoneE164         string     `json:"phoneE164"`
	Role              string     `json:"role"`
	Enabled           bool       `json:"enabled"`
	ActivatedAt       *time.Time `json:"activatedAt,omitempty"`
	SecurityEnabled   bool       `json:"securityEnabled"`
	ActorCreated      bool       `json:"actorCreated,omitempty"`
	RoleCreated       bool       `json:"roleCreated,omitempty"`
	ActorVersion      int        `json:"actorVersion"`
	RoleVersion       int        `json:"roleVersion"`
	CredentialVersion int        `json:"credentialVersion,omitempty"`
}

type ManagedRoleStatusResponse struct {
	ActorID         string      `json:"actorId,omitempty"`
	Exists          bool        `json:"exists"`
	Enabled         bool        `json:"enabled"`
	Activated       bool        `json:"activated"`
	SecurityEnabled bool        `json:"securityEnabled"`
	Reenrollable    bool        `json:"reenrollable"`
	State           string      `json:"state"`
	Role            ManagedRole `json:"role"`
	ActorVersion    int         `json:"actorVersion,omitempty"`
	RoleVersion     int         `json:"roleVersion,omitempty"`
}

type ErrorResponse struct {
	Error map[string]any `json:"error"`
}
