// Code generated by services/dsh/tools/generate-types.mjs; DO NOT EDIT.
// Source: services/dsh/contracts/openapi/dsh.openapi.yaml and referenced path modules.
// Source Graph SHA: 6d9b7ced8696a59c91c3298d3885132adee69d79

package contract

import "time"

type StatusResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type CreateJoiningCaseRequest struct {
	ContactPhoneE164     string `json:"contactPhoneE164"`
	BusinessName         string `json:"businessName"`
	FirstStoreName       string `json:"firstStoreName"`
	ServiceCityID        string `json:"serviceCityId"`
	FirstStoreVerticalID string `json:"firstStoreVerticalId"`
}

type JoiningCaseState string

type JoiningCaseView struct {
	ID                   string           `json:"id"`
	ContactPhoneE164     string           `json:"contactPhoneE164"`
	BusinessName         string           `json:"businessName"`
	FirstStoreName       string           `json:"firstStoreName"`
	ServiceCityID        string           `json:"serviceCityId"`
	FirstStoreVerticalID string           `json:"firstStoreVerticalId"`
	PartnerActorID       string           `json:"partnerActorId,omitempty"`
	State                JoiningCaseState `json:"state"`
	CorrectionReason     string           `json:"correctionReason,omitempty"`
	ReviewedBy           string           `json:"reviewedBy,omitempty"`
	Store                *StoreView       `json:"store,omitempty"`
	Version              int              `json:"version"`
	CreatedAt            time.Time        `json:"createdAt"`
	UpdatedAt            time.Time        `json:"updatedAt"`
}

type JoiningCaseResponse struct {
	Case             JoiningCaseView `json:"case"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type JoiningCaseSummary struct {
	ID                   string           `json:"id"`
	ContactPhoneE164     string           `json:"contactPhoneE164"`
	BusinessName         string           `json:"businessName"`
	FirstStoreName       string           `json:"firstStoreName"`
	ServiceCityID        string           `json:"serviceCityId"`
	FirstStoreVerticalID string           `json:"firstStoreVerticalId"`
	PartnerActorID       string           `json:"partnerActorId,omitempty"`
	State                JoiningCaseState `json:"state"`
	CorrectionReason     string           `json:"correctionReason,omitempty"`
	ReviewedBy           string           `json:"reviewedBy,omitempty"`
	Version              int              `json:"version"`
	CreatedAt            time.Time        `json:"createdAt"`
	UpdatedAt            time.Time        `json:"updatedAt"`
}

type JoiningCaseListResponse struct {
	Cases      []JoiningCaseSummary `json:"cases"`
	NextCursor string               `json:"nextCursor,omitempty"`
}

type CorrectJoiningCaseRequest struct {
	BusinessName         string `json:"businessName"`
	FirstStoreName       string `json:"firstStoreName"`
	ServiceCityID        string `json:"serviceCityId"`
	FirstStoreVerticalID string `json:"firstStoreVerticalId"`
}

type ReviewJoiningCaseRequest struct {
	Decision         string `json:"decision"`
	CorrectionReason string `json:"correctionReason,omitempty"`
}

type StorePublicationReadiness struct {
	Ready         bool   `json:"ready"`
	BlockedReason string `json:"blockedReason,omitempty"`
}

type StoreView struct {
	ID                   string                    `json:"id"`
	PartnerActorID       string                    `json:"partnerActorId"`
	Name                 string                    `json:"name"`
	ServiceCityID        string                    `json:"serviceCityId"`
	PrimaryVerticalID    string                    `json:"primaryVerticalId"`
	Version              int                       `json:"version"`
	PublicationState     PublicationState          `json:"publicationState"`
	PublicationReadiness StorePublicationReadiness `json:"publicationReadiness"`
	PublicationChangedAt *time.Time                `json:"publicationChangedAt,omitempty"`
	Offers               []CatalogStoreOffer       `json:"offers"`
	CreatedAt            time.Time                 `json:"createdAt"`
	UpdatedAt            time.Time                 `json:"updatedAt"`
}

type PublicationState string

type PublicationAction string

type StorePublicationRequest struct {
	State PublicationAction `json:"state"`
}

type StorePublicationResponse struct {
	Store            StoreView `json:"store"`
	IdempotentReplay bool      `json:"idempotentReplay"`
}

type DeliveryOrigin struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type DeliveryAddress struct {
	ID            string    `json:"id"`
	AddressText   string    `json:"addressText"`
	Latitude      float64   `json:"latitude"`
	Longitude     float64   `json:"longitude"`
	ServiceCityID string    `json:"serviceCityId"`
	Version       int       `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type CreateDeliveryAddressRequest struct {
	AddressText   string  `json:"addressText"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	ServiceCityID string  `json:"serviceCityId"`
}

type UpdateDeliveryAddressRequest struct {
	AddressText   string  `json:"addressText"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	ServiceCityID string  `json:"serviceCityId"`
}

type DeliveryAddressResponse struct {
	Address          DeliveryAddress `json:"address"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type DeliveryAddressListResponse struct {
	Addresses  []DeliveryAddress `json:"addresses"`
	NextCursor string            `json:"nextCursor"`
}

type SetStoreDeliveryOriginRequest struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type StoreDeliveryOriginResponse struct {
	StoreID          string          `json:"storeId"`
	OriginVersion    int             `json:"originVersion"`
	Origin           *DeliveryOrigin `json:"origin"`
	IdempotentReplay bool            `json:"idempotentReplay"`
}

type SellUnit string

type CatalogProduct struct {
	ID            string           `json:"id"`
	VerticalID    string           `json:"verticalId"`
	Scope         string           `json:"scope"`
	CanonicalName string           `json:"canonicalName"`
	Brand         string           `json:"brand,omitempty"`
	Active        bool             `json:"active"`
	Version       int              `json:"version"`
	CreatedAt     time.Time        `json:"createdAt"`
	UpdatedAt     time.Time        `json:"updatedAt"`
	Variants      []CatalogVariant `json:"variants"`
	CategoryIds   []string         `json:"categoryIds"`
	Media         []CatalogMedia   `json:"media"`
}

type CatalogVariant struct {
	ID          string              `json:"id"`
	ProductID   string              `json:"productId"`
	Title       string              `json:"title"`
	SellUnit    SellUnit            `json:"sellUnit"`
	Active      bool                `json:"active"`
	Version     int                 `json:"version"`
	Identifiers []CatalogIdentifier `json:"identifiers"`
	CreatedAt   time.Time           `json:"createdAt"`
	UpdatedAt   time.Time           `json:"updatedAt"`
}

type CatalogIdentifier struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type CatalogMedia struct {
	Uri     string `json:"uri"`
	Role    string `json:"role"`
	Ordinal int    `json:"ordinal"`
}

type CreateCatalogProductRequest struct {
	CanonicalName   string   `json:"canonicalName"`
	VerticalID      string   `json:"verticalId"`
	Scope           string   `json:"scope"`
	Brand           string   `json:"brand,omitempty"`
	VariantTitle    string   `json:"variantTitle,omitempty"`
	SellUnit        SellUnit `json:"sellUnit"`
	CategoryIds     []string `json:"categoryIds"`
	IdentifierType  string   `json:"identifierType,omitempty"`
	IdentifierValue string   `json:"identifierValue,omitempty"`
	ImageUri        string   `json:"imageUri,omitempty"`
}

type UpdateCatalogProductRequest struct {
	CanonicalName string `json:"canonicalName"`
	VerticalID    string `json:"verticalId"`
	Scope         string `json:"scope"`
	Brand         string `json:"brand,omitempty"`
	Active        bool   `json:"active"`
}

type CatalogProductResponse struct {
	Product          CatalogProduct `json:"product"`
	IdempotentReplay bool           `json:"idempotentReplay"`
}

type CatalogProductListResponse struct {
	Products []CatalogProduct `json:"products"`
}

type StoreOfferPublicationState string

type CatalogStoreOffer struct {
	OfferID          string                     `json:"offerId"`
	StoreID          string                     `json:"storeId"`
	VariantID        string                     `json:"variantId"`
	ProductID        string                     `json:"productId"`
	ProductName      string                     `json:"productName"`
	Brand            string                     `json:"brand,omitempty"`
	SellUnit         SellUnit                   `json:"sellUnit"`
	ProductActive    bool                       `json:"productActive"`
	VariantActive    bool                       `json:"variantActive"`
	ProductVersion   int                        `json:"productVersion,omitempty"`
	PriceMinor       int                        `json:"priceMinor"`
	Currency         string                     `json:"currency"`
	QuantityPolicy   string                     `json:"quantityPolicy"`
	PricingBasis     string                     `json:"pricingBasis"`
	InventoryPolicy  string                     `json:"inventoryPolicy"`
	Availability     bool                       `json:"availability"`
	PublicationState StoreOfferPublicationState `json:"publicationState"`
	Version          int                        `json:"version"`
	CreatedAt        time.Time                  `json:"createdAt"`
	UpdatedAt        time.Time                  `json:"updatedAt"`
}

type CreateStoreOfferRequest struct {
	VariantID      string `json:"variantId"`
	PriceMinor     int    `json:"priceMinor"`
	QuantityPolicy string `json:"quantityPolicy"`
	PricingBasis   string `json:"pricingBasis"`
}

type UpdateStoreOfferRequest struct {
	PriceMinor       int                        `json:"priceMinor"`
	Availability     bool                       `json:"availability"`
	PublicationState StoreOfferPublicationState `json:"publicationState"`
}

type CatalogStoreOfferResponse struct {
	Offer            CatalogStoreOffer `json:"offer"`
	IdempotentReplay bool              `json:"idempotentReplay"`
}

type CatalogStoreOfferListResponse struct {
	Offers []CatalogStoreOffer `json:"offers"`
}

type CommerceVertical struct {
	ID        string    `json:"id"`
	NameAr    string    `json:"nameAr"`
	NameEn    string    `json:"nameEn"`
	Active    bool      `json:"active"`
	Version   int       `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CreateCommerceVerticalRequest struct {
	ID     string `json:"id"`
	NameAr string `json:"nameAr"`
	NameEn string `json:"nameEn"`
	Active bool   `json:"active"`
}

type CommerceVerticalResponse struct {
	Vertical         CommerceVertical `json:"vertical"`
	IdempotentReplay bool             `json:"idempotentReplay"`
}

type CommerceVerticalListResponse struct {
	Verticals []CommerceVertical `json:"verticals"`
}

type CatalogCategory struct {
	ID               string    `json:"id"`
	VerticalID       string    `json:"verticalId"`
	ParentCategoryID string    `json:"parentCategoryId,omitempty"`
	NameAr           string    `json:"nameAr"`
	NameEn           string    `json:"nameEn"`
	Active           bool      `json:"active"`
	Version          int       `json:"version"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type CreateCatalogCategoryRequest struct {
	ID               string `json:"id"`
	VerticalID       string `json:"verticalId"`
	ParentCategoryID string `json:"parentCategoryId,omitempty"`
	NameAr           string `json:"nameAr"`
	NameEn           string `json:"nameEn"`
	Active           bool   `json:"active"`
}

type CatalogCategoryResponse struct {
	Category CatalogCategory `json:"category"`
}

type CatalogCategoryListResponse struct {
	Categories []CatalogCategory `json:"categories"`
}

type PublicCatalogResponse struct {
	StoreID    string              `json:"storeId"`
	VerticalID string              `json:"verticalId"`
	Categories []CatalogCategory   `json:"categories"`
	Offers     []CatalogStoreOffer `json:"offers"`
}

type PublicStoreView struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	ServiceCity       ServiceCity `json:"serviceCity"`
	PrimaryVerticalID string      `json:"primaryVerticalId"`
	Version           int         `json:"version"`
	PublishedAt       time.Time   `json:"publishedAt"`
	CreatedAt         time.Time   `json:"createdAt"`
	UpdatedAt         time.Time   `json:"updatedAt"`
}

type PublishedStoreListResponse struct {
	Stores []PublicStoreView `json:"stores"`
}

type ServiceCity struct {
	ID            string    `json:"id"`
	DisplayNameAr string    `json:"displayNameAr"`
	Active        bool      `json:"active"`
	Version       int       `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type CreateServiceCityRequest struct {
	ID            string `json:"id"`
	DisplayNameAr string `json:"displayNameAr"`
	Active        bool   `json:"active"`
}

type UpdateServiceCityRequest struct {
	DisplayNameAr string `json:"displayNameAr"`
	Active        bool   `json:"active"`
}

type ServiceCityResponse struct {
	City             ServiceCity `json:"city"`
	IdempotentReplay bool        `json:"idempotentReplay"`
}

type ServiceCityListResponse struct {
	Cities []ServiceCity `json:"cities"`
}

type ServiceabilityStatus string

type ServiceabilityRequest struct {
	StoreID   string `json:"storeId"`
	AddressID string `json:"addressId"`
}

type ServiceabilityEvidence struct {
	StoreID              string    `json:"storeId"`
	StoreVersion         int       `json:"storeVersion"`
	AddressID            string    `json:"addressId"`
	AddressVersion       int       `json:"addressVersion"`
	StoreServiceCityID   string    `json:"storeServiceCityId"`
	AddressServiceCityID string    `json:"addressServiceCityId"`
	ServiceCityID        string    `json:"serviceCityId"`
	ServiceCityVersion   int       `json:"serviceCityVersion"`
	PolicyVersion        string    `json:"policyVersion"`
	EvaluatedAt          time.Time `json:"evaluatedAt"`
}

type ServiceabilityResponse struct {
	Status   ServiceabilityStatus   `json:"status"`
	Evidence ServiceabilityEvidence `json:"evidence"`
}

type CartState string

type CartLine struct {
	ID                        string    `json:"id"`
	CartID                    string    `json:"cartId"`
	StoreOfferID              string    `json:"storeOfferId"`
	VariantID                 string    `json:"variantId"`
	ProductID                 string    `json:"productId"`
	ProductName               string    `json:"productName"`
	VariantTitle              string    `json:"variantTitle"`
	SellUnit                  SellUnit  `json:"sellUnit"`
	PricingBasis              string    `json:"pricingBasis"`
	QuantityBaseUnits         int       `json:"quantityBaseUnits"`
	SelectedModifierOptionIds []string  `json:"selectedModifierOptionIds"`
	UnitPriceMinor            int       `json:"unitPriceMinor"`
	LineAmountMinor           int       `json:"lineAmountMinor"`
	Currency                  string    `json:"currency"`
	OfferVersion              int       `json:"offerVersion"`
	CreatedAt                 time.Time `json:"createdAt"`
	UpdatedAt                 time.Time `json:"updatedAt"`
}

type Cart struct {
	ID        string     `json:"id"`
	StoreID   string     `json:"storeId"`
	State     CartState  `json:"state"`
	Version   int        `json:"version"`
	Lines     []CartLine `json:"lines"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type CartResponse struct {
	Cart             Cart `json:"cart"`
	IdempotentReplay bool `json:"idempotentReplay"`
}

type UpsertCartLineRequest struct {
	StoreID                   string   `json:"storeId"`
	StoreOfferID              string   `json:"storeOfferId"`
	QuantityBaseUnits         int      `json:"quantityBaseUnits"`
	SelectedModifierOptionIds []string `json:"selectedModifierOptionIds"`
}

type UpdateCartLineRequest struct {
	QuantityBaseUnits         int      `json:"quantityBaseUnits"`
	SelectedModifierOptionIds []string `json:"selectedModifierOptionIds"`
}

type CheckoutRequest struct {
	CartID    string `json:"cartId"`
	StoreID   string `json:"storeId"`
	AddressID string `json:"addressId"`
}

type OrderState string

type OrderLine struct {
	ID                         string    `json:"id"`
	OrderID                    string    `json:"orderId"`
	StoreOfferID               string    `json:"storeOfferId"`
	VariantID                  string    `json:"variantId"`
	ProductID                  string    `json:"productId"`
	ProductName                string    `json:"productName"`
	VariantTitle               string    `json:"variantTitle"`
	SellUnit                   SellUnit  `json:"sellUnit"`
	PricingBasis               string    `json:"pricingBasis"`
	RequestedQuantityBaseUnits int       `json:"requestedQuantityBaseUnits"`
	UnitPriceMinor             int       `json:"unitPriceMinor"`
	LineAmountMinor            int       `json:"lineAmountMinor"`
	Currency                   string    `json:"currency"`
	SelectedModifierOptionIds  []string  `json:"selectedModifierOptionIds"`
	CreatedAt                  time.Time `json:"createdAt"`
}

type Order struct {
	ID                           string      `json:"id"`
	ClientActorID                string      `json:"clientActorId"`
	StoreID                      string      `json:"storeId"`
	CartID                       string      `json:"cartId"`
	AddressID                    string      `json:"addressId"`
	AddressVersion               int         `json:"addressVersion"`
	AddressText                  string      `json:"addressText"`
	AddressLatitude              float64     `json:"addressLatitude"`
	AddressLongitude             float64     `json:"addressLongitude"`
	ServiceCityID                string      `json:"serviceCityId"`
	ServiceabilityPolicyVersion  string      `json:"serviceabilityPolicyVersion"`
	ServiceabilityStatus         string      `json:"serviceabilityStatus"`
	ServiceabilityStoreVersion   int         `json:"serviceabilityStoreVersion"`
	ServiceabilityAddressVersion int         `json:"serviceabilityAddressVersion"`
	State                        OrderState  `json:"state"`
	TotalAmountMinor             int         `json:"totalAmountMinor"`
	Currency                     string      `json:"currency"`
	Version                      int         `json:"version"`
	Lines                        []OrderLine `json:"lines"`
	CreatedAt                    time.Time   `json:"createdAt"`
	UpdatedAt                    time.Time   `json:"updatedAt"`
}

type OrderResponse struct {
	Order            Order `json:"order"`
	IdempotentReplay bool  `json:"idempotentReplay"`
}

type OrderListResponse struct {
	Orders []Order `json:"orders"`
}

type OrderTransitionRequest struct {
	State string `json:"state"`
}

type ErrorResponse struct {
	Error map[string]any `json:"error"`
}
