// Code generated by services/identity/tools/generate-password-blocklist.mjs; DO NOT EDIT.
// Source: services/identity/backend/internal/security/password_blocklist_source.txt
// Source version: identity-passwords-v3
// Canonical values SHA-256: d1b796ac7af7b5662140c8b63fcbeb2bf0f3cff4dde01e7116fc294355df2050

package security

var passwordBlocklistGenerated = map[string]struct{}{
	"00000000": {},
	"11111111": {},
	"12345678": {},
	"87654321": {},
	"admin123": {},
	"asdfghjk": {},
	"bthwani1": {},
	"iloveyou": {},
	"letmein1": {},
	"passw0rd": {},
	"password": {},
	"qwerty12": {},
	"qwertyui": {},
	"samrim12": {},
	"welcome1": {},
}
