import { borders, radius, type resolveTheme, spacing, typography } from "@bthwani/design-system";
import { BthwaniButton, BthwaniSurface, useAppearanceTheme } from "@bthwani/design-system/native";
import { createDshMobileClient, type Notification } from "@bthwani/dsh";
import * as Crypto from "expo-crypto";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { currentIdentityState, getUsableIdentityAccessToken } from "../../bootstrap/identity";

function dshClient() { const value = process.env.EXPO_PUBLIC_DSH_API_URL?.trim(); if (!value) throw new Error("DSH_BASE_URL_REQUIRED"); return createDshMobileClient(value, { cryptoRandomUUID: () => Crypto.randomUUID() }); }

export function NotificationsInbox() {
  const theme = useAppearanceTheme(); const styles = useMemo(() => createStyles(theme), [theme]);
  const authenticated = currentIdentityState().kind === "authenticated"; const [items, setItems] = useState<ReadonlyArray<Notification>>([]); const [unreadCount, setUnreadCount] = useState(0); const [loading, setLoading] = useState(authenticated); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!authenticated) return; setLoading(true); setError(""); try { const token = await getUsableIdentityAccessToken(); const response = await dshClient().listNotifications(token, 50); setItems(response.notifications); setUnreadCount(response.unreadCount); } catch (cause) { console.error("DSH partner notifications readback failed", cause); setError("تعذر قراءة الإشعارات. أعد المحاولة."); } finally { setLoading(false); } }, [authenticated]);
  useEffect(() => { void load(); }, [load]);
  async function markRead(item: Notification) { if (item.readAt || busy) return; setBusy(item.id); setError(""); try { const token = await getUsableIdentityAccessToken(); await dshClient().markNotificationRead(token, item.id); await load(); } catch (cause) { console.error("DSH partner notification read-state write failed", cause); setError("تعذر تحديث حالة الإشعار."); } finally { setBusy(""); } }
  return <BthwaniSurface tone="base" style={styles.card} accessibilityLabel="إشعارات الشريك"><View style={styles.header}><Text style={styles.title}>إشعارات الطلبات</Text><Text style={styles.count}>{unreadCount} غير مقروء</Text></View>{!authenticated ? <Text style={styles.muted}>سجّل الدخول لقراءة تحديثات متجرك.</Text> : null}{loading ? <View style={styles.state}><ActivityIndicator color={theme.actionBackground} /><Text style={styles.muted}>جارٍ القراءة…</Text></View> : null}{!loading && authenticated && !items.length ? <Text style={styles.muted}>لا توجد إشعارات حالياً.</Text> : null}{!loading ? items.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={item.title} disabled={Boolean(busy)} onPress={() => void markRead(item)} style={[styles.item, !item.readAt && styles.unread]}><View style={styles.itemHeader}><Text style={styles.itemTitle}>{item.title}</Text>{!item.readAt ? <Text style={styles.dot}>جديد</Text> : null}</View><Text style={styles.body}>{item.body}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleString("ar-YE")}</Text></Pressable>) : null}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{authenticated ? <BthwaniButton busy={loading} disabled={Boolean(busy)} label="تحديث الإشعارات" onPress={() => void load()} variant="secondary" /> : null}</BthwaniSurface>;
}

function createStyles(theme: ReturnType<typeof resolveTheme>) { return StyleSheet.create({ card: { borderColor: theme.borderColor, borderRadius: radius.lg, borderWidth: borders.hairline, gap: spacing[3], padding: spacing[4] }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, title: { ...typography.titleSm, color: theme.color }, count: { ...typography.label, color: theme.interactiveText }, item: { borderColor: theme.borderColor, borderRadius: radius.md, borderWidth: borders.hairline, gap: spacing[1], padding: spacing[3] }, unread: { backgroundColor: theme.actionSoft }, itemHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, itemTitle: { ...typography.bodyStrong, color: theme.color, flex: 1 }, body: { ...typography.bodySm, color: theme.color }, muted: { ...typography.bodySm, color: theme.colorMuted }, dot: { ...typography.label, color: theme.interactiveText }, state: { alignItems: "center", gap: spacing[2], padding: spacing[3] }, error: { ...typography.bodySm, color: theme.warning } }); }
