CREATE TABLE dsh.store_fulfillment_modes_idempotency (
    idempotency_key text PRIMARY KEY,
    request_hash text NOT NULL,
    store_id text NOT NULL,
    partner_actor_id text NOT NULL,
    expected_version integer NOT NULL,
    result_version integer NOT NULL,
    result_fulfillment_modes text[] NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_fulfillment_modes_idempotency_key_chk
        CHECK (length(btrim(idempotency_key)) BETWEEN 8 AND 128),
    CONSTRAINT store_fulfillment_modes_idempotency_hash_chk
        CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_fulfillment_modes_idempotency_version_chk
        CHECK (expected_version > 0 AND result_version IN (expected_version, expected_version + 1)),
    CONSTRAINT store_fulfillment_modes_idempotency_modes_chk
        CHECK (result_fulfillment_modes IN (
            ARRAY['BTHWANI_CAPTAIN']::text[],
            ARRAY['CUSTOMER_PICKUP']::text[],
            ARRAY['BTHWANI_CAPTAIN','CUSTOMER_PICKUP']::text[]
        )),
    CONSTRAINT store_fulfillment_modes_idempotency_facts_uq
        UNIQUE (idempotency_key, request_hash, store_id, partner_actor_id, expected_version),
    CONSTRAINT store_fulfillment_modes_idempotency_store_partner_fk
        FOREIGN KEY (store_id, partner_actor_id)
        REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT
);

CREATE INDEX store_fulfillment_modes_idempotency_partner_idx
    ON dsh.store_fulfillment_modes_idempotency(partner_actor_id, created_at DESC);

CREATE TABLE dsh.store_fulfillment_modes_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    correlation_id text NOT NULL,
    acting_actor_id text NOT NULL,
    partner_actor_id text NOT NULL,
    store_id text NOT NULL,
    from_modes text[] NOT NULL,
    to_modes text[] NOT NULL,
    expected_version integer NOT NULL,
    result_version integer NOT NULL,
    request_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_fulfillment_modes_audit_event_chk
        CHECK (event_type = 'store_fulfillment_modes_updated'),
    CONSTRAINT store_fulfillment_modes_audit_correlation_chk
        CHECK (length(btrim(correlation_id)) BETWEEN 8 AND 128),
    CONSTRAINT store_fulfillment_modes_audit_actor_chk
        CHECK (acting_actor_id = partner_actor_id),
    CONSTRAINT store_fulfillment_modes_audit_version_chk
        CHECK (expected_version > 0 AND result_version = expected_version + 1),
    CONSTRAINT store_fulfillment_modes_audit_hash_chk
        CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_fulfillment_modes_audit_from_modes_chk
        CHECK (from_modes IN (
            ARRAY['BTHWANI_CAPTAIN']::text[],
            ARRAY['CUSTOMER_PICKUP']::text[],
            ARRAY['BTHWANI_CAPTAIN','CUSTOMER_PICKUP']::text[]
        )),
    CONSTRAINT store_fulfillment_modes_audit_to_modes_chk
        CHECK (to_modes IN (
            ARRAY['BTHWANI_CAPTAIN']::text[],
            ARRAY['CUSTOMER_PICKUP']::text[],
            ARRAY['BTHWANI_CAPTAIN','CUSTOMER_PICKUP']::text[]
        )),
    CONSTRAINT store_fulfillment_modes_audit_store_partner_fk
        FOREIGN KEY (store_id, partner_actor_id)
        REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT,
    CONSTRAINT store_fulfillment_modes_audit_idempotency_fk
        FOREIGN KEY (idempotency_key)
        REFERENCES dsh.store_fulfillment_modes_idempotency(idempotency_key) ON DELETE RESTRICT
);

CREATE INDEX store_fulfillment_modes_audit_partner_idx
    ON dsh.store_fulfillment_modes_audit(partner_actor_id, created_at DESC);
