CREATE TABLE dsh.store_captain_memberships (
    id text PRIMARY KEY,
    store_id text NOT NULL,
    partner_actor_id text NOT NULL,
    captain_actor_id text,
    invitation_token_hash text NOT NULL UNIQUE,
    state text NOT NULL,
    version integer NOT NULL DEFAULT 1,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_captain_memberships_id_chk CHECK (length(btrim(id)) BETWEEN 1 AND 128),
    CONSTRAINT store_captain_memberships_token_hash_chk CHECK (invitation_token_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_captain_memberships_state_chk CHECK (state IN ('pending','active','suspended','revoked')),
    CONSTRAINT store_captain_memberships_version_chk CHECK (version > 0),
    CONSTRAINT store_captain_memberships_state_facts_chk CHECK (
        (state = 'pending' AND captain_actor_id IS NULL AND accepted_at IS NULL AND revoked_at IS NULL)
        OR (state IN ('active','suspended') AND captain_actor_id IS NOT NULL AND accepted_at IS NOT NULL AND revoked_at IS NULL)
        OR (state = 'revoked' AND revoked_at IS NOT NULL AND ((captain_actor_id IS NULL AND accepted_at IS NULL) OR (captain_actor_id IS NOT NULL AND accepted_at IS NOT NULL)))
    ),
    CONSTRAINT store_captain_memberships_store_partner_fk
        FOREIGN KEY (store_id, partner_actor_id)
        REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX store_captain_memberships_current_actor_uq
    ON dsh.store_captain_memberships(store_id, captain_actor_id)
    WHERE captain_actor_id IS NOT NULL AND state IN ('active','suspended');

CREATE INDEX store_captain_memberships_store_created_idx
    ON dsh.store_captain_memberships(store_id, created_at DESC, id);

CREATE INDEX store_captain_memberships_captain_idx
    ON dsh.store_captain_memberships(captain_actor_id, created_at DESC)
    WHERE captain_actor_id IS NOT NULL;

CREATE TABLE dsh.store_captain_membership_idempotency (
    idempotency_key text PRIMARY KEY,
    request_hash text NOT NULL,
    operation text NOT NULL,
    membership_id text NOT NULL,
    acting_actor_id text NOT NULL,
    result_state text NOT NULL,
    result_version integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_captain_membership_idempotency_key_chk CHECK (length(btrim(idempotency_key)) BETWEEN 8 AND 128),
    CONSTRAINT store_captain_membership_idempotency_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_captain_membership_idempotency_operation_chk CHECK (operation IN ('invitation_create','invitation_accept','membership_transition')),
    CONSTRAINT store_captain_membership_idempotency_state_chk CHECK (result_state IN ('pending','active','suspended','revoked')),
    CONSTRAINT store_captain_membership_idempotency_version_chk CHECK (result_version > 0),
    CONSTRAINT store_captain_membership_idempotency_membership_fk
        FOREIGN KEY (membership_id) REFERENCES dsh.store_captain_memberships(id) ON DELETE RESTRICT
);

CREATE INDEX store_captain_membership_idempotency_membership_idx
    ON dsh.store_captain_membership_idempotency(membership_id, created_at DESC);

CREATE TABLE dsh.store_captain_membership_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    correlation_id text NOT NULL,
    acting_actor_id text NOT NULL,
    partner_actor_id text NOT NULL,
    store_id text NOT NULL,
    membership_id text NOT NULL,
    from_state text,
    to_state text NOT NULL,
    expected_version integer NOT NULL,
    result_version integer NOT NULL,
    request_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_captain_membership_audit_event_chk CHECK (event_type IN ('invitation_created','invitation_accepted','membership_state_changed')),
    CONSTRAINT store_captain_membership_audit_correlation_chk CHECK (length(btrim(correlation_id)) BETWEEN 8 AND 128),
    CONSTRAINT store_captain_membership_audit_state_chk CHECK (to_state IN ('pending','active','suspended','revoked') AND (from_state IS NULL OR from_state IN ('pending','active','suspended','revoked'))),
    CONSTRAINT store_captain_membership_audit_version_chk CHECK (expected_version >= 0 AND result_version >= expected_version AND result_version <= expected_version + 1),
    CONSTRAINT store_captain_membership_audit_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_captain_membership_audit_store_partner_fk
        FOREIGN KEY (store_id, partner_actor_id) REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT,
    CONSTRAINT store_captain_membership_audit_membership_fk
        FOREIGN KEY (membership_id) REFERENCES dsh.store_captain_memberships(id) ON DELETE RESTRICT,
    CONSTRAINT store_captain_membership_audit_idempotency_fk
        FOREIGN KEY (idempotency_key) REFERENCES dsh.store_captain_membership_idempotency(idempotency_key) ON DELETE RESTRICT
);

CREATE INDEX store_captain_membership_audit_store_idx
    ON dsh.store_captain_membership_audit(store_id, created_at DESC);
