// Code generated by services/identity/tools/generate-types.mjs; DO NOT EDIT.
// Source: services/identity/contracts/openapi/identity.openapi.yaml plus declared path modules.
// Source Git graph SHA: 78bc852c843347d26dd6545c2920aafe4263b809

package identityclient

type IdentityOperation struct {
	Method string
	Path   string
}

var IdentityOperationIdentityHealth = IdentityOperation{Method: "GET", Path: "/identity/health"}
var IdentityOperationIdentityReadiness = IdentityOperation{Method: "GET", Path: "/identity/readiness"}
var IdentityOperationRequestClientRegistrationVerification = IdentityOperation{Method: "POST", Path: "/auth/client/registration/request"}
var IdentityOperationRegisterClient = IdentityOperation{Method: "POST", Path: "/auth/client/register"}
var IdentityOperationLoginClient = IdentityOperation{Method: "POST", Path: "/auth/client/login"}
var IdentityOperationRequestClientRecoveryVerification = IdentityOperation{Method: "POST", Path: "/auth/client/recovery/request"}
var IdentityOperationRecoverClient = IdentityOperation{Method: "POST", Path: "/auth/client/recover"}
var IdentityOperationRequestManagedActivation = IdentityOperation{Method: "POST", Path: "/auth/managed/activation/request"}
var IdentityOperationActivateManagedRole = IdentityOperation{Method: "POST", Path: "/auth/managed/activate"}
var IdentityOperationLoginManagedRole = IdentityOperation{Method: "POST", Path: "/auth/managed/login"}
var IdentityOperationIssueOperatorEnrollmentToken = IdentityOperation{Method: "POST", Path: "/internal/operator-enrollment-tokens"}
var IdentityOperationRequestOperatorEnrollment = IdentityOperation{Method: "POST", Path: "/auth/operator/enrollment/request"}
var IdentityOperationBeginOperatorPasskeyRegistration = IdentityOperation{Method: "POST", Path: "/auth/operator/enrollment/registration/options"}
var IdentityOperationFinishOperatorPasskeyRegistration = IdentityOperation{Method: "POST", Path: "/auth/operator/enrollment/registration/finish"}
var IdentityOperationBeginOperatorPasskeyAuthentication = IdentityOperation{Method: "POST", Path: "/auth/operator/authentication/options"}
var IdentityOperationFinishOperatorPasskeyAuthentication = IdentityOperation{Method: "POST", Path: "/auth/operator/authentication/finish"}
var IdentityOperationRequestOperatorRecovery = IdentityOperation{Method: "POST", Path: "/auth/operator/recovery/request"}
var IdentityOperationBeginOperatorRecoveryPasskeyRegistration = IdentityOperation{Method: "POST", Path: "/auth/operator/recovery/registration/options"}
var IdentityOperationFinishOperatorRecoveryPasskeyRegistration = IdentityOperation{Method: "POST", Path: "/auth/operator/recovery/registration/finish"}
var IdentityOperationBootstrapFirstOperator = IdentityOperation{Method: "POST", Path: "/internal/bootstrap/operator"}
var IdentityOperationRefreshSession = IdentityOperation{Method: "POST", Path: "/auth/refresh"}
var IdentityOperationLogoutSession = IdentityOperation{Method: "POST", Path: "/auth/logout"}
var IdentityOperationReadCurrentSession = IdentityOperation{Method: "GET", Path: "/auth/session"}
var IdentityOperationCreateDevelopmentSession = IdentityOperation{Method: "POST", Path: "/auth/development/session"}
var IdentityOperationProvisionActorRole = IdentityOperation{Method: "POST", Path: "/internal/actor-roles/provision"}
var IdentityOperationSearchActorRoles = IdentityOperation{Method: "GET", Path: "/internal/actor-roles/search"}
var IdentityOperationReadActorRole = IdentityOperation{Method: "GET", Path: "/internal/actors/{actorId}/roles/{role}"}
var IdentityOperationDisableActorRole = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/disable"}
var IdentityOperationEnableActorRole = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/enable"}
var IdentityOperationAuthorizeManagedRoleReenrollment = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/reenrollment"}
var IdentityOperationDisableActorSecurity = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/security/disable"}
var IdentityOperationEnableActorSecurity = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/security/enable"}
var IdentityOperationListActorRoleSessions = IdentityOperation{Method: "GET", Path: "/internal/actors/{actorId}/roles/{role}/sessions"}
var IdentityOperationRevokeActorRoleSessions = IdentityOperation{Method: "DELETE", Path: "/internal/actors/{actorId}/roles/{role}/sessions"}
var IdentityOperationRevokeActorRoleSession = IdentityOperation{Method: "DELETE", Path: "/internal/actors/{actorId}/roles/{role}/sessions/{sessionId}"}
