// Code generated by services/identity/tools/generate-types.mjs; DO NOT EDIT.
// Source: services/identity/contracts/openapi/identity.openapi.yaml plus declared path modules.
// Source Git graph SHA: ceafcc0b1c9100ae68b6dabdf9836c99a6d8df08

package identityclient

import "time"

type StatusResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type ActorType = string

type ManagedActorType = string

type ManagedActivationRole = string

type ControlPanelRole = string

type PhoneRequest struct {
	Phone string `json:"phone"`
}

type ManagedChallengeRequest struct {
	Phone string                `json:"phone"`
	Role  ManagedActivationRole `json:"role"`
}

type OperatorEnrollmentRequest struct {
	Phone                   string `json:"phone"`
	OperatorEnrollmentToken string `json:"operatorEnrollmentToken"`
}

type OperatorEnrollmentTokenIssueRequest struct {
	PhoneE164 string `json:"phoneE164"`
	Role      string `json:"role"`
}

type OperatorEnrollmentToken struct {
	Code        string    `json:"code"`
	MaskedPhone string    `json:"maskedPhone"`
	Role        string    `json:"role"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

type ClientCredentialProofRequest struct {
	Phone            string `json:"phone"`
	Code             string `json:"code"`
	Password         string `json:"password"`
	ClientInstanceID string `json:"clientInstanceId"`
}

type ClientRecoveryProofRequest struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type PasswordLoginRequest struct {
	Phone            string `json:"phone"`
	Password         string `json:"password"`
	ClientInstanceID string `json:"clientInstanceId"`
}

type ManagedPasswordLoginRequest struct {
	Phone            string           `json:"phone"`
	Password         string           `json:"password"`
	Role             ManagedActorType `json:"role"`
	ClientInstanceID string           `json:"clientInstanceId"`
}

type ManagedActivationRequest struct {
	Phone            string                `json:"phone"`
	Role             ManagedActivationRole `json:"role"`
	VerificationCode string                `json:"verificationCode"`
	Password         string                `json:"password"`
	ClientInstanceID string                `json:"clientInstanceId"`
}

type OperatorPasskeyRegistrationOptionsRequest struct {
	Phone                   string `json:"phone"`
	OperatorEnrollmentToken string `json:"operatorEnrollmentToken"`
	VerificationCode        string `json:"verificationCode"`
}

type WebAuthnJSON map[string]any

type PasskeyOptions struct {
	CeremonyID string       `json:"ceremonyId"`
	PublicKey  WebAuthnJSON `json:"publicKey"`
}

type OperatorPasskeyRegistrationFinishRequest struct {
	CeremonyID       string       `json:"ceremonyId"`
	Credential       WebAuthnJSON `json:"credential"`
	ClientInstanceID string       `json:"clientInstanceId"`
}

type OperatorPasskeyAuthenticationFinishRequest struct {
	CeremonyID       string       `json:"ceremonyId"`
	Credential       WebAuthnJSON `json:"credential"`
	ClientInstanceID string       `json:"clientInstanceId"`
}

type OperatorRecoveryRequest struct {
	Phone              string `json:"phone"`
	RecoveryCredential string `json:"recoveryCredential"`
}

type OperatorPasskeyRecoveryRegistrationOptionsRequest struct {
	Phone              string `json:"phone"`
	RecoveryCredential string `json:"recoveryCredential"`
	VerificationCode   string `json:"verificationCode"`
}

type OperatorPasskeyRecoveryFinishRequest struct {
	CeremonyID       string       `json:"ceremonyId"`
	Credential       WebAuthnJSON `json:"credential"`
	ClientInstanceID string       `json:"clientInstanceId"`
}

type OperatorPasskeyRegistrationResponse struct {
	TokenPair          TokenPair `json:"tokenPair"`
	RecoveryCredential string    `json:"recoveryCredential"`
}

type Challenge struct {
	ChallengeID string    `json:"challengeId"`
	MaskedPhone string    `json:"maskedPhone"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

type RefreshRequest struct {
	RefreshToken     string `json:"refreshToken"`
	ClientInstanceID string `json:"clientInstanceId"`
	RefreshRequestID string `json:"refreshRequestId"`
}

type ActorIdentity struct {
	Subject                string    `json:"subject"`
	SessionID              string    `json:"sessionId"`
	Role                   ActorType `json:"role"`
	Surface                string    `json:"surface"`
	ExpiresAt              time.Time `json:"expiresAt"`
	Permissions            []string  `json:"permissions,omitempty"`
	CanManageFinanceAccess bool      `json:"canManageFinanceAccess,omitempty"`
}

type TokenPair struct {
	AccessToken     string        `json:"accessToken"`
	RefreshToken    string        `json:"refreshToken"`
	AccessExpiresAt time.Time     `json:"accessExpiresAt"`
	Identity        ActorIdentity `json:"identity"`
}

type RecoveryResult struct {
	Status string `json:"status"`
}

type ProvisionActorRoleRequest struct {
	PhoneE164 string `json:"phoneE164"`
	Role      string `json:"role"`
}

type ActorRoleView struct {
	ActorID           string     `json:"actorId"`
	PhoneE164         string     `json:"phoneE164"`
	Role              ActorType  `json:"role"`
	Enabled           bool       `json:"enabled"`
	ActivatedAt       *time.Time `json:"activatedAt,omitempty"`
	SecurityEnabled   bool       `json:"securityEnabled"`
	ActorVersion      int        `json:"actorVersion"`
	RoleVersion       int        `json:"roleVersion"`
	CredentialVersion int        `json:"credentialVersion,omitempty"`
	ActorCreated      bool       `json:"actorCreated,omitempty"`
	RoleCreated       bool       `json:"roleCreated,omitempty"`
}

type ActorRoleSearchPage struct {
	Items      []ActorRoleView `json:"items"`
	Limit      int             `json:"limit"`
	NextCursor string          `json:"nextCursor,omitempty"`
}

type OperatorFinanceAccess struct {
	ActorID          string    `json:"actorId"`
	Permission       string    `json:"permission"`
	Enabled          bool      `json:"enabled"`
	Version          int       `json:"version"`
	ChangedByActorID string    `json:"changedByActorId,omitempty"`
	Reason           string    `json:"reason"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type SetOperatorFinanceAccessRequest struct {
	Enabled bool `json:"enabled"`
}

type SessionInfo struct {
	SessionID     string     `json:"sessionId"`
	Role          ActorType  `json:"role"`
	Surface       string     `json:"surface"`
	Version       int        `json:"version"`
	CreatedAt     time.Time  `json:"createdAt"`
	ExpiresAt     time.Time  `json:"expiresAt"`
	LastUsedAt    *time.Time `json:"lastUsedAt,omitempty"`
	CompromisedAt *time.Time `json:"compromisedAt,omitempty"`
}
