// Code generated by tools/dev/generate-identity-types.mjs; DO NOT EDIT.
// Source: services/identity/contracts/identity.openapi.yaml.
// Source Git blob SHA: 4f0e7e2d476003b2b9d69463287ee5871cfa5b21

package identityclient

import "time"

type StatusResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type ActorType = string

type ManagedActorType = string

type ManagedActivationRole = string

type ControlPanelRole = string

type PhoneRequest struct {
	Phone string `json:"phone"`
}

type ManagedChallengeRequest struct {
	Phone          string                `json:"phone"`
	Role           ManagedActivationRole `json:"role"`
	ActivationCode string                `json:"activationCode,omitempty"`
}

type ManagedRecoveryChallengeRequest struct {
	Phone string                `json:"phone"`
	Role  ManagedActivationRole `json:"role"`
}

type OperatorEnrollmentTokenIssueRequest struct {
	PhoneE164 string `json:"phoneE164"`
	Role      string `json:"role"`
}

type OperatorEnrollmentToken struct {
	Code        string                `json:"code"`
	MaskedPhone string                `json:"maskedPhone"`
	Role        ManagedActivationRole `json:"role"`
	ExpiresAt   time.Time             `json:"expiresAt"`
}

type ClientCredentialProofRequest struct {
	Phone             string `json:"phone"`
	Code              string `json:"code"`
	Password          string `json:"password"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type PasswordLoginRequest struct {
	Phone             string `json:"phone"`
	Password          string `json:"password"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type ManagedPasswordLoginRequest struct {
	Phone             string           `json:"phone"`
	Password          string           `json:"password"`
	Role              ManagedActorType `json:"role"`
	DeviceFingerprint string           `json:"deviceFingerprint"`
}

type ManagedActivationRequest struct {
	Phone             string                `json:"phone"`
	Role              ManagedActivationRole `json:"role"`
	ActivationCode    string                `json:"activationCode,omitempty"`
	VerificationCode  string                `json:"verificationCode"`
	Password          string                `json:"password"`
	DeviceFingerprint string                `json:"deviceFingerprint"`
}

type ManagedRecoveryRequest struct {
	Phone    string                `json:"phone"`
	Role     ManagedActivationRole `json:"role"`
	Code     string                `json:"code"`
	Password string                `json:"password"`
}

type OperatorLoginStartRequest struct {
	Phone    string           `json:"phone"`
	Password string           `json:"password"`
	Role     ControlPanelRole `json:"role"`
}

type OperatorLoginCompleteRequest struct {
	Phone             string           `json:"phone"`
	Code              string           `json:"code"`
	Role              ControlPanelRole `json:"role"`
	DeviceFingerprint string           `json:"deviceFingerprint"`
}

type Challenge struct {
	ChallengeID string    `json:"challengeId"`
	MaskedPhone string    `json:"maskedPhone"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

type RefreshRequest struct {
	RefreshToken      string `json:"refreshToken"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type ActorIdentity struct {
	Subject   string    `json:"subject"`
	SessionID string    `json:"sessionId"`
	Role      ActorType `json:"role"`
	Surface   string    `json:"surface"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type TokenPair struct {
	AccessToken     string        `json:"accessToken"`
	RefreshToken    string        `json:"refreshToken"`
	AccessExpiresAt time.Time     `json:"accessExpiresAt"`
	Identity        ActorIdentity `json:"identity"`
}

type RecoveryResult struct {
	Status string `json:"status"`
}

type ProvisionActorRoleRequest struct {
	PhoneE164 string `json:"phoneE164"`
	Role      string `json:"role"`
	Password  string `json:"password,omitempty"`
}

type ActorRoleView struct {
	ActorID         string     `json:"actorId"`
	PhoneE164       string     `json:"phoneE164"`
	Role            ActorType  `json:"role"`
	Enabled         bool       `json:"enabled"`
	ActivatedAt     *time.Time `json:"activatedAt,omitempty"`
	SecurityEnabled bool       `json:"securityEnabled"`
	ActorVersion    int        `json:"actorVersion"`
	RoleVersion     int        `json:"roleVersion"`
	ActorCreated    bool       `json:"actorCreated,omitempty"`
	RoleCreated     bool       `json:"roleCreated,omitempty"`
}

type ActorRoleSearchPage struct {
	Items      []ActorRoleView `json:"items"`
	Limit      int             `json:"limit"`
	NextCursor string          `json:"nextCursor,omitempty"`
}

type PasswordResetRequest struct {
	Password string `json:"password"`
}

type SessionInfo struct {
	SessionID     string     `json:"sessionId"`
	Role          ActorType  `json:"role"`
	Surface       string     `json:"surface"`
	Version       int        `json:"version"`
	CreatedAt     time.Time  `json:"createdAt"`
	ExpiresAt     time.Time  `json:"expiresAt"`
	LastUsedAt    *time.Time `json:"lastUsedAt,omitempty"`
	CompromisedAt *time.Time `json:"compromisedAt,omitempty"`
}
