// Code generated by tools/dev/generate-identity-types.mjs; DO NOT EDIT.
// Source: services/identity/contracts/identity.openapi.yaml.
// Source Git blob SHA: 983663eaa6027604d1808f81e23d54c0b5cc5f48

package identityclient

type IdentityOperation struct {
	Method string
	Path   string
}

var IdentityOperationIdentityHealth = IdentityOperation{Method: "GET", Path: "/identity/health"}
var IdentityOperationIdentityReadiness = IdentityOperation{Method: "GET", Path: "/identity/readiness"}
var IdentityOperationRequestClientRegistrationVerification = IdentityOperation{Method: "POST", Path: "/auth/client/registration/request"}
var IdentityOperationRegisterClient = IdentityOperation{Method: "POST", Path: "/auth/client/register"}
var IdentityOperationLoginClient = IdentityOperation{Method: "POST", Path: "/auth/client/login"}
var IdentityOperationRequestClientRecoveryVerification = IdentityOperation{Method: "POST", Path: "/auth/client/recovery/request"}
var IdentityOperationRecoverClient = IdentityOperation{Method: "POST", Path: "/auth/client/recover"}
var IdentityOperationRequestManagedActivation = IdentityOperation{Method: "POST", Path: "/auth/managed/activation/request"}
var IdentityOperationActivateManagedRole = IdentityOperation{Method: "POST", Path: "/auth/managed/activate"}
var IdentityOperationLoginManagedRole = IdentityOperation{Method: "POST", Path: "/auth/managed/login"}
var IdentityOperationRequestManagedRecoveryVerification = IdentityOperation{Method: "POST", Path: "/auth/managed/recovery/request"}
var IdentityOperationRecoverManagedRole = IdentityOperation{Method: "POST", Path: "/auth/managed/recover"}
var IdentityOperationStartOperatorLogin = IdentityOperation{Method: "POST", Path: "/auth/operator/login/start"}
var IdentityOperationCompleteOperatorLogin = IdentityOperation{Method: "POST", Path: "/auth/operator/login/complete"}
var IdentityOperationRefreshSession = IdentityOperation{Method: "POST", Path: "/auth/refresh"}
var IdentityOperationLogoutSession = IdentityOperation{Method: "POST", Path: "/auth/logout"}
var IdentityOperationReadCurrentSession = IdentityOperation{Method: "GET", Path: "/auth/session"}
var IdentityOperationProvisionActorRole = IdentityOperation{Method: "POST", Path: "/internal/actor-roles/provision"}
var IdentityOperationBootstrapPlatformOwner = IdentityOperation{Method: "POST", Path: "/internal/bootstrap/platform-owner"}
var IdentityOperationIssueManagedActivationCode = IdentityOperation{Method: "POST", Path: "/internal/managed-activation-codes"}
var IdentityOperationSearchActorRoles = IdentityOperation{Method: "GET", Path: "/internal/actor-roles/search"}
var IdentityOperationReadActorRole = IdentityOperation{Method: "GET", Path: "/internal/actors/{actorId}/roles/{role}"}
var IdentityOperationDisableActorRole = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/disable"}
var IdentityOperationEnableActorRole = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/enable"}
var IdentityOperationAuthorizeManagedRoleReenrollment = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/roles/{role}/reenrollment"}
var IdentityOperationDisableActorSecurity = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/security/disable"}
var IdentityOperationEnableActorSecurity = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/security/enable"}
var IdentityOperationResetOperatorPassword = IdentityOperation{Method: "POST", Path: "/internal/actors/{actorId}/operator-password/reset"}
var IdentityOperationListActorRoleSessions = IdentityOperation{Method: "GET", Path: "/internal/actors/{actorId}/roles/{role}/sessions"}
var IdentityOperationRevokeActorRoleSessions = IdentityOperation{Method: "DELETE", Path: "/internal/actors/{actorId}/roles/{role}/sessions"}
var IdentityOperationRevokeActorRoleSession = IdentityOperation{Method: "DELETE", Path: "/internal/actors/{actorId}/roles/{role}/sessions/{sessionId}"}
