package postgres

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "github.com/lib/pq"
)

const SchemaVersion = 61

type MigrationRecord struct {
	Version int
	Name    string
	SHA256  string
}

var requiredTables = []struct {
	name             string
	columns          []string
	forbiddenColumns []string
	constraints      []string
	indexes          []string
}{
	{name: "dsh.schema_migrations", columns: []string{"version", "name", "sha256", "applied_at"}, constraints: []string{"schema_migrations_pkey"}},
	{name: "dsh.stores", columns: []string{"id", "partner_actor_id", "name", "version", "created_at", "updated_at", "publication_state", "publication_changed_at", "delivery_origin_latitude", "delivery_origin_longitude", "delivery_origin_version", "delivery_origin_updated_at", "service_city_id", "primary_vertical_id", "fulfillment_modes"}, constraints: []string{"stores_pkey", "stores_id_partner_actor_uq", "stores_name_length_chk", "stores_version_positive_chk", "stores_publication_state_chk", "stores_delivery_origin_pair_chk", "stores_delivery_origin_latitude_chk", "stores_delivery_origin_longitude_chk", "stores_delivery_origin_version_chk", "stores_delivery_origin_updated_at_chk", "stores_service_city_fk", "stores_primary_vertical_fk", "stores_fulfillment_modes_chk"}, indexes: []string{"stores_partner_actor_idx", "stores_publication_state_idx", "stores_service_city_idx", "stores_primary_vertical_idx", "stores_operator_updated_idx"}},
	{name: "dsh.joining_cases", columns: []string{"id", "contact_phone_e164", "business_name", "first_store_name", "partner_actor_id", "originating_field_actor_id", "origin", "state", "correction_reason", "reviewed_by", "store_id", "version", "created_at", "updated_at", "first_store_service_city_id", "first_store_vertical_id", "first_store_fulfillment_modes", "first_store_latitude", "first_store_longitude", "commission_rate_bps", "settlement_period", "financial_profile_id", "financial_profile_state"}, constraints: []string{"joining_cases_pkey", "joining_cases_phone_length_chk", "joining_cases_business_name_chk", "joining_cases_store_name_chk", "joining_cases_state_chk", "joining_cases_version_positive_chk", "joining_cases_store_fk", "joining_cases_service_city_fk", "joining_cases_first_store_vertical_fk", "joining_cases_origin_chk", "joining_cases_field_actor_chk", "joining_cases_store_origin_pair_chk", "joining_cases_store_origin_latitude_chk", "joining_cases_store_origin_longitude_chk", "joining_cases_commission_rate_chk", "joining_cases_settlement_period_chk", "joining_cases_financial_profile_state_chk", "joining_cases_financial_terms_pair_chk", "joining_cases_first_store_fulfillment_modes_chk"}, indexes: []string{"joining_cases_active_phone_uq", "joining_cases_partner_actor_uq", "joining_cases_state_idx", "joining_cases_service_city_idx", "joining_cases_first_store_vertical_idx", "joining_cases_field_actor_idx", "joining_cases_financial_profile_id_uq", "joining_cases_financial_profile_state_idx"}},
	{name: "dsh.joining_case_financial_profile_outbox", columns: []string{"id", "case_id", "idempotency_key", "request_hash", "correlation_id", "acting_actor_id", "partner_actor_id", "origin", "commission_rate_bps", "settlement_period", "financial_profile_id", "state", "attempts", "last_error", "next_attempt_at", "created_at", "updated_at"}, constraints: []string{"joining_case_financial_profile_outbox_pkey", "joining_case_financial_outbox_case_uq", "joining_case_financial_outbox_idempotency_uq", "joining_case_financial_outbox_case_fk", "joining_case_financial_outbox_origin_chk", "joining_case_financial_outbox_commission_chk", "joining_case_financial_outbox_settlement_chk", "joining_case_financial_outbox_state_chk", "joining_case_financial_outbox_attempts_chk"}, indexes: []string{"joining_case_financial_outbox_pending_idx"}},
	{name: "dsh.joining_case_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "case_id", "operation", "result_version", "result_state", "result_partner_actor_id", "result_store_id", "result_correction_reason", "created_at"}, constraints: []string{"joining_case_mutation_idempotency_pkey", "joining_case_idempotency_facts_uq", "joining_case_idempotency_operation_chk", "joining_case_idempotency_state_chk", "joining_case_idempotency_version_chk", "joining_case_idempotency_case_fk"}, indexes: []string{"joining_case_idempotency_case_idx"}},
	{name: "dsh.joining_case_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "case_id", "from_state", "to_state", "result_version", "request_hash", "partner_actor_id", "store_id", "correction_reason", "created_at"}, constraints: []string{"joining_case_audit_pkey", "joining_case_audit_event_type_chk", "joining_case_audit_event_idempotency_uq", "joining_case_audit_case_fk", "joining_case_audit_version_chk"}, indexes: []string{"joining_case_audit_case_idx"}},
	{name: "dsh.store_publication_idempotency", columns: []string{"idempotency_key", "request_hash", "store_id", "requested_state", "expected_version", "result_version", "result_state", "result_publication_changed_at", "result_updated_at", "created_at"}, constraints: []string{"store_publication_idempotency_pkey", "store_publication_idempotency_facts_uq", "store_publication_idempotency_state_chk", "store_publication_idempotency_store_fk"}, indexes: []string{"store_publication_idempotency_store_idx"}},
	{name: "dsh.store_publication_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "store_id", "from_state", "to_state", "expected_version", "result_version", "request_hash", "requested_state", "created_at"}, constraints: []string{"store_publication_audit_pkey", "store_publication_audit_event_type_chk", "store_publication_audit_event_idempotency_uq", "store_publication_audit_idempotency_fk"}, indexes: []string{"store_publication_audit_store_idx"}},
	{name: "dsh.delivery_addresses", columns: []string{"id", "client_actor_id", "address_text", "latitude", "longitude", "version", "created_at", "updated_at", "service_city_id"}, constraints: []string{"delivery_addresses_pkey", "delivery_addresses_text_chk", "delivery_addresses_latitude_chk", "delivery_addresses_longitude_chk", "delivery_addresses_version_chk", "delivery_addresses_service_city_fk"}, indexes: []string{"delivery_addresses_client_idx", "delivery_addresses_service_city_idx"}},
	{name: "dsh.delivery_address_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "address_id", "client_actor_id", "operation", "expected_version", "created_at"}, constraints: []string{"delivery_address_mutation_idempotency_pkey", "delivery_address_idempotency_facts_uq", "delivery_address_idempotency_operation_chk", "delivery_address_idempotency_expected_version_chk", "delivery_address_idempotency_address_fk"}, indexes: []string{"delivery_address_idempotency_client_idx"}},
	{name: "dsh.delivery_address_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "client_actor_id", "address_id", "expected_version", "result_version", "request_hash", "created_at"}, constraints: []string{"delivery_address_audit_pkey", "delivery_address_audit_event_type_chk", "delivery_address_audit_event_idempotency_uq", "delivery_address_audit_address_fk", "delivery_address_audit_expected_version_chk", "delivery_address_audit_result_version_chk"}, indexes: []string{"delivery_address_audit_client_idx"}},
	{name: "dsh.store_origin_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "store_id", "partner_actor_id", "expected_version", "created_at"}, constraints: []string{"store_origin_mutation_idempotency_pkey", "store_origin_idempotency_facts_uq", "store_origin_idempotency_expected_version_chk", "store_origin_idempotency_store_partner_fk"}, indexes: []string{"store_origin_idempotency_partner_idx"}},
	{name: "dsh.store_origin_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "partner_actor_id", "store_id", "expected_version", "result_version", "request_hash", "created_at"}, constraints: []string{"store_origin_audit_pkey", "store_origin_audit_event_type_chk", "store_origin_audit_event_idempotency_uq", "store_origin_audit_store_partner_fk", "store_origin_audit_expected_version_chk", "store_origin_audit_result_version_chk"}, indexes: []string{"store_origin_audit_partner_idx"}},
	{name: "dsh.service_cities", columns: []string{"id", "display_name_ar", "active", "version", "created_at", "updated_at"}, constraints: []string{"service_cities_pkey", "service_cities_id_chk", "service_cities_display_name_ar_chk", "service_cities_version_chk"}, indexes: []string{"service_cities_display_name_ar_uq", "service_cities_active_idx"}},
	{name: "dsh.service_city_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "city_id", "operation", "expected_version", "result_version", "result_display_name_ar", "result_active", "created_at"}, constraints: []string{"service_city_mutation_idempotency_pkey", "service_city_idempotency_facts_uq", "service_city_idempotency_operation_chk", "service_city_idempotency_expected_version_chk", "service_city_idempotency_result_version_chk", "service_city_idempotency_city_fk"}, indexes: []string{"service_city_idempotency_city_idx"}},
	{name: "dsh.service_city_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "city_id", "from_version", "result_version", "from_active", "to_active", "request_hash", "display_name_ar", "created_at"}, constraints: []string{"service_city_audit_pkey", "service_city_audit_event_type_chk", "service_city_audit_event_idempotency_uq", "service_city_audit_city_fk", "service_city_audit_from_version_chk", "service_city_audit_result_version_chk", "service_city_audit_display_name_ar_chk"}, indexes: []string{"service_city_audit_city_idx"}},
	{name: "dsh.commerce_verticals", columns: []string{"id", "name_ar", "name_en", "active", "version", "created_at", "updated_at", "catalog_model"}, constraints: []string{"commerce_verticals_pkey", "commerce_verticals_id_chk", "commerce_verticals_name_ar_chk", "commerce_verticals_name_en_chk", "commerce_verticals_version_chk", "commerce_verticals_catalog_model_chk"}, indexes: []string{"commerce_verticals_name_en_uq", "commerce_verticals_active_idx"}},
	{name: "dsh.catalog_categories", columns: []string{"id", "vertical_id", "parent_category_id", "name_ar", "name_en", "active", "version", "created_at", "updated_at"}, constraints: []string{"catalog_categories_pkey", "catalog_categories_id_chk", "catalog_categories_name_ar_chk", "catalog_categories_name_en_chk", "catalog_categories_version_chk", "catalog_categories_vertical_fk", "catalog_categories_vertical_id_uq", "catalog_categories_parent_same_vertical_fk"}, indexes: []string{"catalog_categories_vertical_idx"}},
	{name: "dsh.catalog_attribute_definitions", columns: []string{"id", "vertical_id", "code", "name_ar", "value_kind", "active", "version", "created_at", "updated_at"}, constraints: []string{"catalog_attribute_definitions_pkey", "catalog_attribute_definitions_code_chk", "catalog_attribute_definitions_name_chk", "catalog_attribute_definitions_kind_chk", "catalog_attribute_definitions_version_chk", "catalog_attribute_definitions_vertical_fk", "catalog_attribute_definitions_vertical_code_uq"}, indexes: []string{}},
	{name: "dsh.catalog_products", columns: []string{"id", "vertical_id", "scope", "store_id", "canonical_name", "brand", "active", "version", "created_at", "updated_at", "description"}, constraints: []string{"catalog_products_pkey", "catalog_products_name_chk", "catalog_products_scope_chk", "catalog_products_version_chk", "catalog_products_vertical_fk", "catalog_products_store_fk", "catalog_products_scope_store_chk", "catalog_products_description_chk"}, indexes: []string{"catalog_products_vertical_idx", "catalog_products_name_prefix_idx", "catalog_products_store_idx"}},
	{name: "dsh.catalog_product_variants", columns: []string{"id", "product_id", "title", "measurement_kind", "base_unit", "active", "version", "created_at", "updated_at"}, constraints: []string{"catalog_product_variants_pkey", "catalog_product_variants_title_chk", "catalog_product_variants_version_chk", "catalog_product_variants_product_fk", "catalog_product_variants_product_title_uq", "catalog_product_variants_measurement_kind_chk", "catalog_product_variants_base_unit_chk", "catalog_product_variants_measurement_identity_chk"}, indexes: []string{"catalog_product_variants_product_idx"}},
	{name: "dsh.catalog_variant_identifiers", columns: []string{"id", "variant_id", "identifier_type", "identifier_value", "created_at"}, constraints: []string{"catalog_variant_identifiers_pkey", "catalog_variant_identifiers_type_chk", "catalog_variant_identifiers_value_chk", "catalog_variant_identifiers_variant_fk"}, indexes: []string{"catalog_variant_identifiers_variant_idx", "catalog_variant_identifiers_value_uq"}},
	{name: "dsh.catalog_product_categories", columns: []string{"product_id", "category_id", "created_at"}, constraints: []string{"catalog_product_categories_pkey", "catalog_product_categories_product_fk", "catalog_product_categories_category_fk"}, indexes: []string{"catalog_product_categories_category_idx"}},
	{name: "dsh.catalog_product_attribute_values", columns: []string{"product_id", "attribute_id", "text_value", "integer_value", "decimal_value", "boolean_value", "enum_value", "date_value", "measurement_unit"}, constraints: []string{"catalog_product_attribute_values_pkey", "catalog_product_attribute_values_product_fk", "catalog_product_attribute_values_attribute_fk", "catalog_product_attribute_values_one_value_chk"}, indexes: []string{}},
	{name: "dsh.catalog_media", columns: []string{"id", "product_id", "uri", "media_role", "ordinal", "created_at"}, constraints: []string{"catalog_media_pkey", "catalog_media_uri_chk", "catalog_media_role_chk", "catalog_media_ordinal_chk", "catalog_media_product_fk", "catalog_media_product_ordinal_uq"}, indexes: []string{}},
	{name: "dsh.catalog_media_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "product_id", "expected_version", "result_version", "created_at"}, constraints: []string{"catalog_media_mutation_idempotency_pkey", "catalog_media_idempotency_expected_version_chk", "catalog_media_idempotency_result_version_chk", "catalog_media_idempotency_product_fk"}, indexes: []string{"catalog_media_idempotency_product_idx"}},
	{name: "dsh.catalog_media_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "product_id", "from_version", "result_version", "media_count", "request_hash", "created_at"}, constraints: []string{"catalog_media_audit_pkey", "catalog_media_audit_event_chk", "catalog_media_audit_event_idempotency_uq", "catalog_media_audit_product_fk", "catalog_media_audit_from_version_chk", "catalog_media_audit_result_version_chk", "catalog_media_audit_media_count_chk"}, indexes: []string{"catalog_media_audit_product_idx"}},
	{name: "dsh.catalog_media_assets", columns: []string{"id", "product_id", "idempotency_key", "expected_version", "object_key", "uri", "content_sha256", "content_type", "byte_size", "media_role", "state", "cleanup_attempts", "last_cleanup_error", "created_at", "retired_at", "cleaned_at"}, constraints: []string{"catalog_media_assets_pkey", "catalog_media_assets_product_fk", "catalog_media_assets_idempotency_key_key", "catalog_media_assets_expected_version_chk", "catalog_media_assets_object_key_key", "catalog_media_assets_uri_key", "catalog_media_assets_sha_chk", "catalog_media_assets_content_type_chk", "catalog_media_assets_byte_size_chk", "catalog_media_assets_role_chk", "catalog_media_assets_state_chk", "catalog_media_assets_cleanup_attempts_chk", "catalog_media_assets_retired_at_chk", "catalog_media_assets_cleaned_at_chk"}, indexes: []string{"catalog_media_assets_product_idx", "catalog_media_assets_cleanup_idx"}},
	{name: "dsh.catalog_store_offers", columns: []string{"id", "store_id", "variant_id", "price_minor", "currency", "quantity_policy", "quantity_min_base_units", "quantity_max_base_units", "quantity_step_base_units", "pricing_basis", "pricing_unit_base_units", "inventory_policy", "inventory_on_hand_base_units", "inventory_reserved_base_units", "availability", "publication_state", "version", "created_at", "updated_at"}, constraints: []string{"catalog_store_offers_pkey", "catalog_store_offers_store_fk", "catalog_store_offers_variant_fk", "catalog_store_offers_price_chk", "catalog_store_offers_currency_chk", "catalog_store_offers_quantity_policy_chk", "catalog_store_offers_pricing_basis_chk", "catalog_store_offers_inventory_policy_chk", "catalog_store_offers_inventory_on_hand_chk", "catalog_store_offers_inventory_reserved_chk", "catalog_store_offers_inventory_mode_chk", "catalog_store_offers_state_chk", "catalog_store_offers_version_chk", "catalog_store_offers_store_variant_uq", "catalog_store_offers_pricing_unit_chk", "catalog_store_offers_quantity_policy_bounds_chk"}, indexes: []string{"catalog_store_offers_store_idx", "catalog_store_offers_public_idx", "catalog_store_offers_quantity_idx", "catalog_store_offers_inventory_idx"}},
	{name: "dsh.catalog_store_offer_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "offer_id", "operation", "result_version", "created_at"}, constraints: []string{"catalog_store_offer_mutation_idempotency_pkey", "catalog_store_offer_idempotency_operation_chk", "catalog_store_offer_idempotency_version_chk", "catalog_store_offer_idempotency_offer_fk"}, indexes: []string{"catalog_store_offer_idempotency_offer_idx"}},
	{name: "dsh.catalog_product_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "product_id", "operation", "result_version", "created_at"}, constraints: []string{"catalog_product_mutation_idempotency_pkey", "catalog_product_idempotency_operation_chk", "catalog_product_idempotency_version_chk", "catalog_product_idempotency_product_fk"}, indexes: []string{"catalog_product_idempotency_product_idx"}},
	{name: "dsh.catalog_product_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "product_id", "from_version", "result_version", "request_hash", "canonical_name", "brand", "vertical_id", "scope", "created_at"}, constraints: []string{"catalog_product_audit_pkey", "catalog_product_audit_event_type_chk", "catalog_product_audit_event_idempotency_uq", "catalog_product_audit_product_fk", "catalog_product_audit_version_chk", "catalog_product_audit_scope_chk"}, indexes: []string{"catalog_product_audit_product_idx"}},
	{name: "dsh.catalog_store_offer_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "offer_id", "from_state", "to_state", "expected_version", "result_version", "request_hash", "store_id", "variant_id", "price_minor", "currency", "availability", "created_at"}, constraints: []string{"catalog_store_offer_audit_pkey", "catalog_store_offer_audit_event_type_chk", "catalog_store_offer_audit_event_idempotency_uq", "catalog_store_offer_audit_offer_fk", "catalog_store_offer_audit_store_fk", "catalog_store_offer_audit_variant_fk", "catalog_store_offer_audit_price_chk", "catalog_store_offer_audit_currency_chk", "catalog_store_offer_audit_version_chk"}, indexes: []string{"catalog_store_offer_audit_store_idx"}},
	{name: "dsh.catalog_product_proposals", columns: []string{"id", "partner_actor_id", "vertical_id", "category_id", "proposed_name", "proposed_brand", "proposed_variant_title", "proposed_measurement_kind", "proposed_base_unit", "proposed_identifier_type", "proposed_identifier_value", "proposed_image_uri", "proposed_attribute_values", "proposed_variant_attribute_values", "state", "correction_reason", "reviewed_by", "version", "created_at", "updated_at"}, constraints: []string{"catalog_product_proposals_pkey", "catalog_product_proposals_name_chk", "catalog_product_proposals_identifier_type_chk", "catalog_product_proposals_state_chk", "catalog_product_proposals_version_chk", "catalog_product_proposals_vertical_fk", "catalog_product_proposals_category_fk", "catalog_product_proposals_variant_title_chk", "catalog_product_proposals_measurement_kind_chk", "catalog_product_proposals_base_unit_chk", "catalog_product_proposals_measurement_identity_chk", "catalog_product_proposal_attribute_values_array_chk", "catalog_product_proposal_variant_attribute_values_array_chk"}, indexes: []string{"catalog_product_proposals_partner_idx", "catalog_product_proposals_review_idx"}},
	{name: "dsh.catalog_import_runs", columns: []string{"id", "acting_actor_id", "source_sha256", "mode", "state", "accepted_count", "conflict_count", "created_at"}, constraints: []string{"catalog_import_runs_pkey", "catalog_import_runs_mode_chk", "catalog_import_runs_state_chk", "catalog_import_runs_count_chk"}, indexes: []string{"catalog_import_runs_source_mode_uq"}},
	{name: "dsh.catalog_import_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "run_id", "operation", "result_state", "created_at"}, constraints: []string{"catalog_import_mutation_idempotency_pkey", "catalog_import_idempotency_operation_chk", "catalog_import_idempotency_state_chk", "catalog_import_idempotency_run_fk"}, indexes: []string{"catalog_import_idempotency_facts_uq", "catalog_import_idempotency_run_idx"}},
	{name: "dsh.catalog_import_run_items", columns: []string{"run_id", "row_number", "stable_key", "payload", "classification", "product_id", "variant_id", "error_code", "error_message", "committed", "created_at", "updated_at"}, constraints: []string{"catalog_import_run_items_pkey", "catalog_import_run_items_run_fk", "catalog_import_run_items_product_fk", "catalog_import_run_items_variant_fk", "catalog_import_run_items_row_chk", "catalog_import_run_items_key_chk", "catalog_import_run_items_classification_chk", "catalog_import_run_items_commit_chk"}, indexes: []string{"catalog_import_run_items_classification_idx"}},
	{name: "dsh.catalog_import_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "run_id", "source_sha256", "from_state", "to_state", "accepted_count", "conflict_count", "request_hash", "created_at"}, constraints: []string{"catalog_import_audit_pkey", "catalog_import_audit_event_type_chk", "catalog_import_audit_event_idempotency_uq", "catalog_import_audit_run_fk", "catalog_import_audit_count_chk", "catalog_import_audit_sha_chk"}, indexes: []string{"catalog_import_audit_run_idx"}},
	{name: "dsh.catalog_registry_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "entity_type", "entity_id", "created_at"}, constraints: []string{"catalog_registry_mutation_idempotency_pkey", "catalog_registry_mutation_entity_chk", "catalog_registry_mutation_entity_key_uq"}, indexes: []string{"catalog_registry_mutation_entity_idx"}},
	{name: "dsh.catalog_registry_audit_events", columns: []string{"id", "entity_type", "entity_id", "action", "acting_actor_id", "correlation_id", "reason", "expected_version", "resulting_version", "before_state", "after_state", "recorded_at"}, constraints: []string{"catalog_registry_audit_events_pkey", "catalog_registry_audit_entity_chk", "catalog_registry_audit_action_chk", "catalog_registry_audit_actor_chk", "catalog_registry_audit_correlation_chk", "catalog_registry_audit_reason_chk", "catalog_registry_audit_version_chk"}, indexes: []string{"catalog_registry_audit_entity_history_idx"}},
	{name: "dsh.commerce_carts", columns: []string{"id", "client_actor_id", "store_id", "state", "version", "created_at", "updated_at"}, constraints: []string{"commerce_carts_pkey", "commerce_carts_state_chk", "commerce_carts_version_chk", "commerce_carts_store_fk"}, indexes: []string{"commerce_carts_client_store_open_uq", "commerce_carts_client_idx"}},
	{name: "dsh.commerce_cart_lines", columns: []string{"id", "cart_id", "store_offer_id", "variant_id", "quantity_base_units", "selected_modifier_option_ids", "removed_at", "created_at", "updated_at"}, constraints: []string{"commerce_cart_lines_pkey", "commerce_cart_lines_quantity_chk", "commerce_cart_lines_cart_fk", "commerce_cart_lines_offer_fk", "commerce_cart_lines_variant_fk"}, indexes: []string{"commerce_cart_lines_cart_idx", "commerce_cart_lines_cart_offer_uq", "commerce_cart_lines_modifier_idx"}},
	{name: "dsh.commerce_cart_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "cart_id", "line_id", "operation", "expected_cart_version", "result_cart_version", "created_at"}, constraints: []string{"commerce_cart_mutation_idempotency_pkey", "commerce_cart_idempotency_operation_chk", "commerce_cart_idempotency_expected_version_chk", "commerce_cart_idempotency_result_version_chk", "commerce_cart_idempotency_cart_fk", "commerce_cart_idempotency_line_fk"}, indexes: []string{"commerce_cart_idempotency_cart_idx"}},
	{name: "dsh.commerce_cart_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "cart_id", "line_id", "store_offer_id", "from_version", "result_version", "request_hash", "quantity_base_units", "created_at"}, constraints: []string{"commerce_cart_audit_pkey", "commerce_cart_audit_event_type_chk", "commerce_cart_audit_event_idempotency_uq", "commerce_cart_audit_cart_fk", "commerce_cart_audit_line_fk", "commerce_cart_audit_result_version_chk"}, indexes: []string{"commerce_cart_audit_cart_idx"}},
	{name: "dsh.commerce_orders", columns: []string{"id", "client_actor_id", "store_id", "cart_id", "fulfillment_mode", "address_id", "address_version", "address_text", "address_latitude", "address_longitude", "service_city_id", "serviceability_policy_version", "serviceability_status", "serviceability_store_version", "serviceability_address_version", "state", "subtotal_amount_minor", "discount_minor", "promotion_id", "promotion_code", "total_amount_minor", "currency", "payment_intent_id", "payment_method", "payment_state", "version", "created_at", "updated_at"}, constraints: []string{"commerce_orders_pkey", "commerce_orders_fulfillment_evidence_chk", "commerce_orders_state_chk", "commerce_orders_total_chk", "commerce_orders_currency_chk", "commerce_orders_version_chk", "commerce_orders_store_fk", "commerce_orders_cart_fk", "commerce_orders_service_city_fk", "commerce_orders_payment_method_chk", "commerce_orders_payment_state_chk", "commerce_orders_payment_binding_chk"}, indexes: []string{"commerce_orders_client_idx", "commerce_orders_store_state_idx", "commerce_orders_payment_intent_uq", "commerce_orders_payment_state_idx", "commerce_order_pickup_queue_idx"}},
	{name: "dsh.commerce_financial_handoff_outbox", columns: []string{"id", "effect_type", "source_ref", "order_id", "payment_intent_id", "captain_actor_id", "partner_actor_id", "amount_minor", "reason", "idempotency_key", "correlation_id", "state", "attempts", "last_error", "next_attempt_at", "acting_actor_id", "created_at", "updated_at"}, constraints: []string{"commerce_financial_handoff_outbox_pkey", "commerce_financial_handoff_outbox_source_uq", "commerce_financial_handoff_outbox_idempotency_uq", "commerce_financial_handoff_outbox_order_fk", "commerce_financial_handoff_outbox_effect_chk", "commerce_financial_handoff_outbox_source_chk", "commerce_financial_handoff_outbox_payment_chk", "commerce_financial_handoff_outbox_idempotency_chk", "commerce_financial_handoff_outbox_correlation_chk", "commerce_financial_handoff_outbox_state_chk", "commerce_financial_handoff_outbox_attempts_chk", "commerce_financial_handoff_outbox_shape_chk", "commerce_financial_handoff_outbox_actor_chk"}, indexes: []string{"commerce_financial_handoff_outbox_pending_idx"}},
	{name: "dsh.commerce_order_store_cash_handoffs", columns: []string{"order_id", "assignment_id", "store_id", "captain_actor_id", "partner_actor_id", "amount_minor", "state", "completion_idempotency_key", "confirmation_idempotency_key", "confirmation_request_hash", "store_confirmed_by", "store_confirmed_at", "settled_at", "version", "created_at", "updated_at"}, constraints: []string{"commerce_order_store_cash_handoffs_pkey", "commerce_order_store_cash_handoffs_order_fk", "commerce_order_store_cash_handoffs_assignment_fk", "commerce_order_store_cash_handoffs_store_fk", "commerce_order_store_cash_handoffs_amount_chk", "commerce_order_store_cash_handoffs_state_chk", "commerce_order_store_cash_handoffs_actor_chk", "commerce_order_store_cash_handoffs_version_chk", "commerce_order_store_cash_handoffs_completion_key_chk", "commerce_order_store_cash_handoffs_confirmation_chk"}, indexes: []string{"commerce_order_store_cash_handoffs_assignment_id_key", "commerce_order_store_cash_handof_completion_idempotency_key_key", "commerce_order_store_cash_hand_confirmation_idempotency_key_key", "commerce_order_store_cash_handoffs_partner_pending_idx"}},
	{name: "dsh.commerce_promotions", columns: []string{"id", "code", "name_ar", "description_ar", "kind", "value_minor", "max_discount_minor", "funding_source", "store_id", "service_city_id", "state", "starts_at", "ends_at", "redemption_limit", "redeemed_count", "version", "created_by_actor_id", "created_at", "updated_at"}, constraints: []string{"commerce_promotions_pkey", "commerce_promotions_code_chk", "commerce_promotions_name_chk", "commerce_promotions_kind_chk", "commerce_promotions_value_chk", "commerce_promotions_percentage_chk", "commerce_promotions_max_discount_chk", "commerce_promotions_funding_chk", "commerce_promotions_state_chk", "commerce_promotions_window_chk", "commerce_promotions_limit_chk", "commerce_promotions_redeemed_chk", "commerce_promotions_version_chk", "commerce_promotions_store_fk", "commerce_promotions_city_fk"}, indexes: []string{"commerce_promotions_code_uq", "commerce_promotions_public_idx"}},
	{name: "dsh.commerce_promotion_redemptions", columns: []string{"id", "promotion_id", "client_actor_id", "order_id", "code", "discount_minor", "created_at"}, constraints: []string{"commerce_promotion_redemptions_pkey", "commerce_promotion_redemptions_discount_chk", "commerce_promotion_redemptions_promotion_fk", "commerce_promotion_redemptions_order_fk"}, indexes: []string{"commerce_promotion_redemptions_client_promotion_uq", "commerce_promotion_redemptions_promotion_idx"}},
	{name: "dsh.discovery_content", columns: []string{"id", "kind", "title_ar", "body_ar", "media_uri", "target_type", "target_id", "service_city_id", "state", "starts_at", "ends_at", "ordinal", "version", "created_by_actor_id", "created_at", "updated_at"}, constraints: []string{"discovery_content_pkey", "discovery_content_kind_chk", "discovery_content_title_chk", "discovery_content_target_type_chk", "discovery_content_target_chk", "discovery_content_state_chk", "discovery_content_window_chk", "discovery_content_ordinal_chk", "discovery_content_version_chk"}, indexes: []string{"discovery_content_public_idx"}},
	{name: "dsh.discovery_content_events", columns: []string{"id", "client_event_id", "content_id", "event_type", "client_session_id", "client_actor_id", "order_id", "occurred_at"}, constraints: []string{"discovery_content_events_pkey", "discovery_content_events_client_event_id_key", "discovery_content_events_content_fk", "discovery_content_events_order_fk", "discovery_content_events_type_chk", "discovery_content_events_session_chk", "discovery_content_events_conversion_chk", "discovery_content_events_actor_chk"}, indexes: []string{"discovery_content_events_content_idx", "discovery_content_events_conversion_order_uq"}},
	{name: "dsh.commerce_marketing_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "resource_type", "resource_id", "operation", "created_at"}, constraints: []string{"commerce_marketing_mutation_idempotency_pkey", "commerce_marketing_idempotency_resource_chk", "commerce_marketing_idempotency_operation_chk"}, indexes: []string{}},
	{name: "dsh.commerce_multi_store_checkouts", columns: []string{"id", "client_actor_id", "state", "version", "child_count", "successful_child_count", "failed_child_count", "created_at", "updated_at"}, constraints: []string{"commerce_multi_store_checkouts_pkey", "commerce_multi_store_checkouts_state_chk", "commerce_multi_store_checkouts_version_chk", "commerce_multi_store_checkouts_child_count_chk", "commerce_multi_store_checkouts_success_count_chk", "commerce_multi_store_checkouts_failed_count_chk"}, indexes: []string{"commerce_multi_store_checkouts_client_idx"}},
	{name: "dsh.commerce_multi_store_checkout_children", columns: []string{"id", "checkout_id", "child_index", "cart_id", "store_id", "address_id", "cart_version", "fulfillment_mode", "promotion_code", "order_id", "state", "failure_code", "failure_message", "version", "created_at", "updated_at"}, constraints: []string{"commerce_multi_store_checkout_children_pkey", "commerce_multi_store_checkout_children_state_chk", "commerce_multi_store_checkout_children_index_chk", "commerce_multi_store_checkout_children_cart_version_chk", "commerce_multi_store_checkout_children_version_chk", "commerce_multi_store_checkout_children_order_state_chk", "commerce_multi_store_checkout_children_checkout_fk", "commerce_multi_store_checkout_children_cart_fk", "commerce_multi_store_checkout_children_store_fk", "commerce_multi_store_checkout_children_order_fk"}, indexes: []string{"commerce_multi_store_checkout_children_index_uq", "commerce_multi_store_checkout_children_cart_uq", "commerce_multi_store_checkout_children_store_uq", "commerce_multi_store_checkout_children_order_uq", "commerce_multi_store_checkout_children_checkout_idx"}},
	{name: "dsh.commerce_multi_store_checkout_idempotency", columns: []string{"idempotency_key", "request_hash", "checkout_id", "operation", "expected_version", "result_version", "created_at"}, constraints: []string{"commerce_multi_store_checkout_idempotency_pkey", "commerce_multi_store_checkout_idempotency_operation_chk", "commerce_multi_store_checkout_idempotency_expected_version_chk", "commerce_multi_store_checkout_idempotency_result_version_chk", "commerce_multi_store_checkout_idempotency_checkout_fk"}, indexes: []string{"commerce_multi_store_checkout_idempotency_checkout_idx"}},
	{name: "dsh.commerce_order_payment_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "order_id", "payment_intent_id", "from_state", "to_state", "amount_minor", "created_at"}, constraints: []string{"commerce_order_payment_audit_pkey", "commerce_order_payment_audit_event_chk", "commerce_order_payment_audit_idempotency_uq", "commerce_order_payment_audit_amount_chk", "commerce_order_payment_audit_order_fk"}, indexes: []string{"commerce_order_payment_audit_order_idx"}},
	{name: "dsh.commerce_order_delivery_proofs", columns: []string{"order_id", "client_actor_id", "code_ciphertext", "code_verifier", "code_key_id", "state", "verified_by", "verified_at", "created_at", "updated_at", "proof_type"}, forbiddenColumns: []string{"code", "code_hash"}, constraints: []string{"commerce_order_delivery_proofs_pkey", "commerce_order_delivery_proof_order_fk", "commerce_order_delivery_proof_state_chk", "commerce_order_delivery_proof_verified_chk", "commerce_order_delivery_proof_type_chk", "commerce_order_delivery_proof_material_chk"}, indexes: []string{"commerce_order_delivery_proofs_client_idx"}},
	{name: "dsh.commerce_order_ratings", columns: []string{"order_id", "client_actor_id", "store_id", "rating", "review", "idempotency_key", "request_hash", "created_at"}, constraints: []string{"commerce_order_ratings_pkey", "commerce_order_ratings_order_fk", "commerce_order_ratings_store_fk", "commerce_order_ratings_actor_chk", "commerce_order_ratings_rating_chk", "commerce_order_ratings_review_chk", "commerce_order_ratings_request_hash_chk", "commerce_order_ratings_idempotency_key_key"}, indexes: []string{"commerce_order_ratings_client_idx", "commerce_order_ratings_store_idx"}},
	{name: "dsh.commerce_order_rating_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "order_id", "client_actor_id", "store_id", "rating", "review", "request_hash", "created_at"}, constraints: []string{"commerce_order_rating_audit_pkey", "commerce_order_rating_audit_event_chk", "commerce_order_rating_audit_event_idempotency_uq", "commerce_order_rating_audit_order_fk", "commerce_order_rating_audit_store_fk", "commerce_order_rating_audit_rating_chk", "commerce_order_rating_audit_review_chk", "commerce_order_rating_audit_request_hash_chk"}, indexes: []string{"commerce_order_rating_audit_order_idx"}},
	{name: "dsh.commerce_order_conversation_messages", columns: []string{"id", "order_id", "sender_actor_id", "sender_role", "body", "idempotency_key", "request_hash", "correlation_id", "created_at"}, constraints: []string{"commerce_order_conversation_messages_pkey", "commerce_order_conversation_messages_order_fk", "commerce_order_conversation_messages_sender_role_chk", "commerce_order_conversation_messages_actor_chk", "commerce_order_conversation_messages_body_chk", "commerce_order_conversation_messages_request_hash_chk", "commerce_order_conversation_messages_correlation_chk", "commerce_order_conversation_messages_idempotency_key_key"}, indexes: []string{"commerce_order_conversation_messages_order_idx", "commerce_order_conversation_messages_sender_idx"}},
	{name: "dsh.commerce_order_conversation_read_state", columns: []string{"actor_id", "message_id", "read_at"}, constraints: []string{"commerce_order_conversation_read_state_pkey", "commerce_order_conversation_read_state_actor_chk", "commerce_order_conversation_read_state_message_fk"}, indexes: []string{"commerce_order_conversation_read_state_actor_idx"}},
	{name: "dsh.commerce_order_lines", columns: []string{"id", "order_id", "store_offer_id", "variant_id", "product_id", "product_name", "variant_title", "measurement_kind", "base_unit", "pricing_basis", "quantity_policy", "quantity_min_base_units", "quantity_max_base_units", "quantity_step_base_units", "pricing_unit_base_units", "requested_quantity_base_units", "final_quantity_base_units", "inventory_reserved_base_units", "unit_price_minor", "modifier_amount_minor", "line_amount_minor", "currency", "selected_modifier_option_ids", "created_at"}, constraints: []string{"commerce_order_lines_pkey", "commerce_order_lines_quantity_chk", "commerce_order_lines_price_chk", "commerce_order_lines_pricing_chk", "commerce_order_lines_currency_chk", "commerce_order_lines_order_fk", "commerce_order_lines_order_offer_uq", "commerce_order_lines_final_quantity_chk", "commerce_order_lines_modifier_amount_chk", "commerce_order_lines_inventory_reserved_chk"}, indexes: []string{"commerce_order_lines_order_idx"}},
	{name: "dsh.catalog_attribute_enum_options", columns: []string{"attribute_id", "option_value", "active", "ordinal", "created_at"}, constraints: []string{"catalog_attribute_enum_options_pkey", "catalog_attribute_enum_options_attribute_fk", "catalog_attribute_enum_options_value_chk", "catalog_attribute_enum_options_ordinal_chk"}, indexes: []string{"catalog_attribute_enum_options_active_idx"}},
	{name: "dsh.catalog_category_attribute_rules", columns: []string{"category_id", "attribute_id", "required", "filterable", "variant_axis", "version", "created_at", "updated_at"}, constraints: []string{"catalog_category_attribute_rules_pkey", "catalog_category_attribute_rules_category_fk", "catalog_category_attribute_rules_attribute_fk", "catalog_category_attribute_rules_version_chk"}, indexes: []string{"catalog_category_attribute_rules_attribute_idx"}},
	{name: "dsh.catalog_variant_attribute_values", columns: []string{"variant_id", "attribute_id", "text_value", "integer_value", "decimal_value", "boolean_value", "enum_value", "date_value", "measurement_unit"}, constraints: []string{"catalog_variant_attribute_values_pkey", "catalog_variant_attribute_values_variant_fk", "catalog_variant_attribute_values_attribute_fk", "catalog_variant_attribute_values_one_value_chk"}, indexes: []string{"catalog_variant_attribute_values_attribute_idx"}},
	{name: "dsh.catalog_product_proposal_idempotency", columns: []string{"idempotency_key", "request_hash", "proposal_id", "operation", "result_version", "created_at"}, constraints: []string{"catalog_product_proposal_idempotency_pkey", "catalog_product_proposal_idempotency_operation_chk", "catalog_product_proposal_idempotency_version_chk", "catalog_product_proposal_idempotency_proposal_fk"}, indexes: []string{"catalog_product_proposal_idempotency_proposal_idx"}},
	{name: "dsh.catalog_product_proposal_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "proposal_id", "from_state", "to_state", "result_version", "request_hash", "created_at"}, constraints: []string{"catalog_product_proposal_audit_pkey", "catalog_product_proposal_audit_event_type_chk", "catalog_product_proposal_audit_event_idempotency_uq", "catalog_product_proposal_audit_proposal_fk", "catalog_product_proposal_audit_version_chk"}, indexes: []string{"catalog_product_proposal_audit_proposal_idx"}},
	{name: "dsh.catalog_storefront_sections", columns: []string{"id", "store_id", "name_ar", "name_en", "ordinal", "active", "version", "created_at", "updated_at"}, constraints: []string{"catalog_storefront_sections_pkey", "catalog_storefront_sections_store_fk", "catalog_storefront_sections_name_chk", "catalog_storefront_sections_name_en_chk", "catalog_storefront_sections_ordinal_chk", "catalog_storefront_sections_version_chk", "catalog_storefront_sections_store_name_uq"}, indexes: []string{"catalog_storefront_sections_store_idx"}},
	{name: "dsh.catalog_storefront_section_offers", columns: []string{"section_id", "offer_id", "ordinal", "created_at"}, constraints: []string{"catalog_storefront_section_offers_pkey", "catalog_storefront_section_offers_section_fk", "catalog_storefront_section_offers_offer_fk", "catalog_storefront_section_offers_ordinal_chk"}, indexes: []string{"catalog_storefront_section_offers_offer_idx"}},
	{name: "dsh.catalog_modifier_groups", columns: []string{"id", "store_id", "name_ar", "required", "min_selections", "max_selections", "active", "version", "created_at", "updated_at"}, constraints: []string{"catalog_modifier_groups_pkey", "catalog_modifier_groups_store_fk", "catalog_modifier_groups_name_chk", "catalog_modifier_groups_selection_chk", "catalog_modifier_groups_version_chk"}, indexes: []string{"catalog_modifier_groups_store_idx"}},
	{name: "dsh.catalog_modifier_options", columns: []string{"id", "group_id", "name_ar", "price_delta_minor", "availability", "ordinal", "version", "created_at", "updated_at"}, constraints: []string{"catalog_modifier_options_pkey", "catalog_modifier_options_group_fk", "catalog_modifier_options_name_chk", "catalog_modifier_options_price_chk", "catalog_modifier_options_ordinal_chk", "catalog_modifier_options_version_chk"}, indexes: []string{"catalog_modifier_options_group_idx"}},
	{name: "dsh.catalog_store_offer_modifier_groups", columns: []string{"offer_id", "group_id", "ordinal", "created_at"}, constraints: []string{"catalog_store_offer_modifier_groups_pkey", "catalog_store_offer_modifier_groups_offer_fk", "catalog_store_offer_modifier_groups_group_fk", "catalog_store_offer_modifier_groups_ordinal_chk"}, indexes: []string{"catalog_store_offer_modifier_groups_group_idx"}},
	{name: "dsh.commerce_order_line_modifier_snapshots", columns: []string{"order_line_id", "option_id", "option_name_ar", "price_delta_minor", "created_at"}, constraints: []string{"commerce_order_line_modifier_snapshots_pkey", "commerce_order_line_modifier_snapshots_line_fk", "commerce_order_line_modifier_snapshots_name_chk", "commerce_order_line_modifier_snapshots_price_chk"}, indexes: []string{"commerce_order_line_modifier_snapshots_option_idx"}},
	{name: "dsh.commerce_order_line_attribute_snapshots", columns: []string{"order_line_id", "attribute_id", "attribute_code", "value_kind", "text_value", "integer_value", "decimal_value", "boolean_value", "enum_value", "date_value", "measurement_unit", "created_at"}, constraints: []string{"commerce_order_line_attribute_snapshots_pkey", "commerce_order_line_attribute_snapshots_line_fk", "commerce_order_line_attribute_snapshots_kind_chk", "commerce_order_line_attribute_snapshots_one_value_chk"}, indexes: []string{"commerce_order_line_attribute_snapshots_attribute_idx"}},
	{name: "dsh.commerce_order_checkout_idempotency", columns: []string{"idempotency_key", "request_hash", "cart_id", "order_id", "result_version", "created_at"}, constraints: []string{"commerce_order_checkout_idempotency_pkey", "commerce_order_checkout_idempotency_version_chk", "commerce_order_checkout_idempotency_cart_fk", "commerce_order_checkout_idempotency_order_fk"}, indexes: []string{"commerce_order_checkout_cart_uq"}},
	{name: "dsh.commerce_order_transition_idempotency", columns: []string{"idempotency_key", "request_hash", "order_id", "requested_state", "expected_version", "result_version", "created_at"}, constraints: []string{"commerce_order_transition_idempotency_pkey", "commerce_order_transition_state_chk", "commerce_order_transition_expected_version_chk", "commerce_order_transition_result_version_chk", "commerce_order_transition_order_fk"}, indexes: []string{"commerce_order_transition_order_idx"}},
	{name: "dsh.commerce_order_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "order_id", "from_state", "to_state", "from_version", "result_version", "request_hash", "created_at"}, constraints: []string{"commerce_order_audit_pkey", "commerce_order_audit_event_type_chk", "commerce_order_audit_event_idempotency_uq", "commerce_order_audit_order_fk", "commerce_order_audit_result_version_chk"}, indexes: []string{"commerce_order_audit_order_idx"}},
	{name: "dsh.captain_admissions", columns: []string{"id", "actor_id", "contact_phone_e164", "state", "availability_state", "version", "created_at", "updated_at"}, constraints: []string{"captain_admissions_pkey", "captain_admissions_actor_id_key", "captain_admissions_state_chk", "captain_admissions_availability_chk", "captain_admissions_version_chk", "captain_admissions_phone_chk", "captain_admissions_identity_state_chk", "captain_admissions_pending_availability_chk", "captain_admissions_suspended_availability_chk"}, indexes: []string{"captain_admissions_pending_phone_uq", "captain_admissions_dispatch_idx"}},
	{name: "dsh.captain_admission_idempotency", columns: []string{"idempotency_key", "request_hash", "admission_id", "operation", "result_version", "result_state", "result_actor_id", "created_at"}, constraints: []string{"captain_admission_idempotency_pkey", "captain_admission_idempotency_facts_uq", "captain_admission_idempotency_operation_chk", "captain_admission_idempotency_state_chk", "captain_admission_idempotency_version_chk", "captain_admission_idempotency_admission_fk"}, indexes: []string{"captain_admission_idempotency_admission_idx"}},
	{name: "dsh.captain_admission_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "admission_id", "actor_id", "from_state", "to_state", "from_version", "result_version", "request_hash", "reason", "created_at"}, constraints: []string{"captain_admission_audit_pkey", "captain_admission_audit_event_type_chk", "captain_admission_audit_event_idempotency_uq", "captain_admission_audit_admission_fk", "captain_admission_audit_version_chk", "captain_admission_audit_reason_chk"}, indexes: []string{"captain_admission_audit_admission_idx"}},
	{name: "dsh.captain_dispatch_offers", columns: []string{"id", "order_id", "captain_actor_id", "source_store_id", "state", "expires_at", "version", "idempotency_key", "request_hash", "created_at", "updated_at"}, constraints: []string{"captain_dispatch_offers_pkey", "captain_dispatch_offers_idempotency_key_key", "captain_dispatch_offers_state_chk", "captain_dispatch_offers_version_chk", "captain_dispatch_offers_order_fk", "captain_dispatch_offers_source_store_fk", "captain_dispatch_offers_source_store_id_chk"}, indexes: []string{"captain_dispatch_offers_order_active_uq", "captain_dispatch_offers_captain_active_uq", "captain_dispatch_offers_captain_idx", "captain_dispatch_offers_order_idx"}},
	{name: "dsh.captain_assignments", columns: []string{"id", "order_id", "captain_actor_id", "accepted_offer_id", "state", "version", "custody_started_at", "terminal_result", "terminal_at", "created_at", "updated_at"}, constraints: []string{"captain_assignments_pkey", "captain_assignments_accepted_offer_id_key", "captain_assignments_state_chk", "captain_assignments_result_chk", "captain_assignments_custody_chk", "captain_assignments_version_chk", "captain_assignments_order_fk", "captain_assignments_offer_fk"}, indexes: []string{"captain_assignments_order_active_uq", "captain_assignments_captain_active_uq", "captain_assignments_captain_idx", "captain_assignments_order_idx"}},
	{name: "dsh.captain_handoffs", columns: []string{"assignment_id", "order_id", "store_id", "state", "version", "store_confirmed_at", "captain_picked_up_at", "created_at", "updated_at"}, constraints: []string{"captain_handoffs_pkey", "captain_handoffs_state_chk", "captain_handoffs_confirmation_chk", "captain_handoffs_version_chk", "captain_handoffs_assignment_fk", "captain_handoffs_order_fk", "captain_handoffs_store_fk"}, indexes: []string{}},
	{name: "dsh.captain_operation_idempotency", columns: []string{"idempotency_key", "request_hash", "operation", "admission_id", "order_id", "offer_id", "assignment_id", "result_version", "created_at"}, constraints: []string{"captain_operation_idempotency_pkey", "captain_operation_idempotency_facts_uq", "captain_operation_idempotency_operation_chk", "captain_operation_idempotency_version_chk", "captain_operation_idempotency_order_fk", "captain_operation_idempotency_offer_fk", "captain_operation_idempotency_assignment_fk", "captain_operation_idempotency_admission_fk"}, indexes: []string{"captain_operation_idempotency_order_idx"}},
	{name: "dsh.captain_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "order_id", "offer_id", "assignment_id", "captain_actor_id", "from_state", "to_state", "result_version", "request_hash", "created_at"}, constraints: []string{"captain_audit_pkey", "captain_audit_event_type_chk", "captain_audit_event_idempotency_uq", "captain_audit_result_version_chk", "captain_audit_order_fk", "captain_audit_offer_fk", "captain_audit_assignment_fk"}, indexes: []string{"captain_audit_order_idx"}},
	{name: "dsh.captain_location_snapshots", columns: []string{"assignment_id", "order_id", "captain_actor_id", "latitude", "longitude", "version", "last_idempotency_key", "last_request_hash", "updated_at"}, constraints: []string{"captain_location_snapshots_pkey", "captain_location_snapshots_latitude_chk", "captain_location_snapshots_longitude_chk", "captain_location_snapshots_version_chk", "captain_location_snapshots_assignment_fk", "captain_location_snapshots_order_fk"}, indexes: []string{"captain_location_snapshots_order_idx"}},
	{name: "dsh.captain_location_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "assignment_id", "order_id", "captain_actor_id", "result_version", "result_latitude", "result_longitude", "result_updated_at", "created_at"}, constraints: []string{"captain_location_mutation_idempotency_pkey", "captain_location_idempotency_facts_uq", "captain_location_idempotency_version_chk", "captain_location_idempotency_latitude_chk", "captain_location_idempotency_longitude_chk", "captain_location_idempotency_assignment_fk", "captain_location_idempotency_order_fk"}, indexes: []string{"captain_location_idempotency_assignment_idx"}},
	{name: "dsh.captain_location_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "order_id", "assignment_id", "captain_actor_id", "result_version", "latitude", "longitude", "request_hash", "created_at"}, constraints: []string{"captain_location_audit_pkey", "captain_location_audit_event_type_chk", "captain_location_audit_event_idempotency_uq", "captain_location_audit_version_chk", "captain_location_audit_latitude_chk", "captain_location_audit_longitude_chk", "captain_location_audit_assignment_fk", "captain_location_audit_order_fk"}, indexes: []string{"captain_location_audit_assignment_idx"}},
	{name: "dsh.notification_read_state", columns: []string{"actor_id", "notification_id", "read_at"}, constraints: []string{"notification_read_state_pkey", "notification_read_state_actor_chk", "notification_read_state_notification_chk"}, indexes: []string{"notification_read_state_actor_idx"}},
	{name: "dsh.field_admissions", columns: []string{"id", "actor_id", "contact_phone_e164", "state", "version", "created_at", "updated_at"}, constraints: []string{"field_admissions_pkey", "field_admissions_actor_id_key", "field_admissions_state_chk", "field_admissions_version_chk", "field_admissions_phone_chk", "field_admissions_identity_state_chk"}, indexes: []string{"field_admissions_pending_phone_uq", "field_admissions_state_idx"}},
	{name: "dsh.field_admission_idempotency", columns: []string{"idempotency_key", "request_hash", "admission_id", "operation", "result_version", "result_state", "result_actor_id", "created_at"}, constraints: []string{"field_admission_idempotency_pkey", "field_admission_idempotency_facts_uq", "field_admission_idempotency_operation_chk", "field_admission_idempotency_state_chk", "field_admission_idempotency_version_chk", "field_admission_idempotency_admission_fk"}, indexes: []string{"field_admission_idempotency_admission_idx"}},
	{name: "dsh.field_admission_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "admission_id", "actor_id", "from_state", "to_state", "from_version", "result_version", "request_hash", "created_at"}, constraints: []string{"field_admission_audit_pkey", "field_admission_audit_event_type_chk", "field_admission_audit_event_idempotency_uq", "field_admission_audit_admission_fk", "field_admission_audit_version_chk"}, indexes: []string{"field_admission_audit_admission_idx"}},
	{name: "dsh.catalog_variant_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "variant_id", "operation", "result_version", "created_at"}, constraints: []string{"catalog_variant_mutation_idempotency_pkey", "catalog_variant_idempotency_operation_chk", "catalog_variant_idempotency_version_chk", "catalog_variant_idempotency_variant_fk"}, indexes: []string{"catalog_variant_idempotency_variant_idx"}},
	{name: "dsh.catalog_variant_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "variant_id", "product_id", "from_version", "result_version", "request_hash", "title", "measurement_kind", "base_unit", "active", "created_at"}, constraints: []string{"catalog_variant_audit_pkey", "catalog_variant_audit_event_type_chk", "catalog_variant_audit_event_idempotency_uq", "catalog_variant_audit_variant_fk", "catalog_variant_audit_product_fk", "catalog_variant_audit_version_chk", "catalog_variant_audit_measurement_kind_chk", "catalog_variant_audit_base_unit_chk", "catalog_variant_audit_measurement_identity_chk"}, indexes: []string{"catalog_variant_audit_variant_idx"}},
	{name: "dsh.catalog_attribute_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "attribute_id", "operation", "result_version", "created_at"}, constraints: []string{"catalog_attribute_mutation_idempotency_pkey", "catalog_attribute_idempotency_operation_chk", "catalog_attribute_idempotency_version_chk", "catalog_attribute_idempotency_attribute_fk"}, indexes: []string{"catalog_attribute_idempotency_attribute_idx"}},
	{name: "dsh.client_favorite_stores", columns: []string{"client_actor_id", "store_id", "created_at"}, constraints: []string{"client_favorite_stores_pkey", "client_favorite_stores_actor_chk", "client_favorite_stores_store_fk"}, indexes: []string{"client_favorite_stores_client_idx"}},
	{name: "dsh.client_favorite_store_mutation_idempotency", columns: []string{"idempotency_key", "request_hash", "client_actor_id", "store_id", "operation", "result_is_favorite", "created_at"}, constraints: []string{"client_favorite_store_mutation_idempotency_pkey", "client_favorite_store_idempotency_facts_uq", "client_favorite_store_idempotency_actor_chk", "client_favorite_store_idempotency_operation_chk", "client_favorite_store_idempotency_store_fk"}, indexes: []string{"client_favorite_store_idempotency_client_idx"}},
	{name: "dsh.client_favorite_store_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "client_actor_id", "store_id", "result_is_favorite", "request_hash", "created_at"}, constraints: []string{"client_favorite_store_audit_pkey", "client_favorite_store_audit_event_type_chk", "client_favorite_store_audit_event_idempotency_uq", "client_favorite_store_audit_actor_chk", "client_favorite_store_audit_store_fk"}, indexes: []string{"client_favorite_store_audit_client_idx"}},
	{name: "dsh.field_commission_publication_outbox", columns: []string{"id", "store_id", "field_actor_id", "vertical_id", "idempotency_key", "request_hash", "correlation_id", "state", "attempts", "last_error", "next_attempt_at", "created_at", "updated_at"}, constraints: []string{"field_commission_publication_outbox_pkey", "field_commission_publication_outbox_store_uq", "field_commission_publication_outbox_idempotency_uq", "field_commission_publication_outbox_store_fk", "field_commission_publication_outbox_field_actor_chk", "field_commission_publication_outbox_vertical_chk", "field_commission_publication_outbox_hash_chk", "field_commission_publication_outbox_correlation_chk", "field_commission_publication_outbox_state_chk", "field_commission_publication_outbox_attempts_chk"}, indexes: []string{"field_commission_publication_outbox_pending_idx"}},
	{name: "dsh.store_profile_media_assets", columns: []string{"id", "joining_case_id", "store_id", "idempotency_key", "request_hash", "expected_case_version", "object_key", "uri", "content_sha256", "content_type", "byte_size", "media_role", "state", "created_at", "attached_at", "retired_at", "cleanup_attempts", "last_cleanup_error"}, constraints: []string{"store_profile_media_assets_pkey", "store_profile_media_assets_joining_case_id_fkey", "store_profile_media_assets_store_id_fkey", "store_profile_media_assets_idempotency_key_key", "store_profile_media_assets_object_key_key", "store_profile_media_assets_uri_key", "store_profile_media_case_version_chk", "store_profile_media_sha_chk", "store_profile_media_content_type_chk", "store_profile_media_byte_size_chk", "store_profile_media_role_chk", "store_profile_media_state_chk", "store_profile_media_retired_at_chk", "store_profile_media_attached_at_chk"}, indexes: []string{"store_profile_media_case_active_uq", "store_profile_media_store_active_uq", "store_profile_media_case_idx", "store_profile_media_cleanup_idx"}},
	{name: "dsh.store_profile_media_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "joining_case_id", "result_version", "request_hash", "created_at"}, constraints: []string{"store_profile_media_audit_pkey", "store_profile_media_audit_idempotency_key_key", "store_profile_media_audit_event_chk", "store_profile_media_audit_version_chk", "store_profile_media_audit_idempotency_key_fkey", "store_profile_media_audit_joining_case_id_fkey"}, indexes: []string{"store_profile_media_audit_case_idx"}},
	{name: "dsh.store_fulfillment_modes_idempotency", columns: []string{"idempotency_key", "request_hash", "store_id", "partner_actor_id", "expected_version", "result_version", "result_fulfillment_modes", "created_at"}, constraints: []string{"store_fulfillment_modes_idempotency_pkey", "store_fulfillment_modes_idempotency_key_chk", "store_fulfillment_modes_idempotency_hash_chk", "store_fulfillment_modes_idempotency_version_chk", "store_fulfillment_modes_idempotency_modes_chk", "store_fulfillment_modes_idempotency_facts_uq", "store_fulfillment_modes_idempotency_store_partner_fk"}, indexes: []string{"store_fulfillment_modes_idempotency_partner_idx"}},
	{name: "dsh.store_fulfillment_modes_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "partner_actor_id", "store_id", "from_modes", "to_modes", "expected_version", "result_version", "request_hash", "created_at"}, constraints: []string{"store_fulfillment_modes_audit_pkey", "store_fulfillment_modes_audit_idempotency_key_key", "store_fulfillment_modes_audit_event_chk", "store_fulfillment_modes_audit_correlation_chk", "store_fulfillment_modes_audit_actor_chk", "store_fulfillment_modes_audit_version_chk", "store_fulfillment_modes_audit_hash_chk", "store_fulfillment_modes_audit_from_modes_chk", "store_fulfillment_modes_audit_to_modes_chk", "store_fulfillment_modes_audit_store_partner_fk", "store_fulfillment_modes_audit_idempotency_fk"}, indexes: []string{"store_fulfillment_modes_audit_partner_idx"}},
	{name: "dsh.store_captain_memberships", columns: []string{"id", "store_id", "partner_actor_id", "captain_actor_id", "invitation_token_hash", "state", "version", "expires_at", "accepted_at", "revoked_at", "created_at", "updated_at"}, constraints: []string{"store_captain_memberships_pkey", "store_captain_memberships_invitation_token_hash_key", "store_captain_memberships_id_chk", "store_captain_memberships_token_hash_chk", "store_captain_memberships_state_chk", "store_captain_memberships_version_chk", "store_captain_memberships_state_facts_chk", "store_captain_memberships_store_partner_fk"}, indexes: []string{"store_captain_memberships_current_actor_uq", "store_captain_memberships_store_created_idx", "store_captain_memberships_captain_idx"}},
	{name: "dsh.store_captain_membership_idempotency", columns: []string{"idempotency_key", "request_hash", "operation", "membership_id", "acting_actor_id", "result_state", "result_version", "created_at"}, constraints: []string{"store_captain_membership_idempotency_pkey", "store_captain_membership_idempotency_key_chk", "store_captain_membership_idempotency_hash_chk", "store_captain_membership_idempotency_operation_chk", "store_captain_membership_idempotency_state_chk", "store_captain_membership_idempotency_version_chk", "store_captain_membership_idempotency_membership_fk"}, indexes: []string{"store_captain_membership_idempotency_membership_idx"}},
	{name: "dsh.store_captain_membership_audit", columns: []string{"id", "event_type", "idempotency_key", "correlation_id", "acting_actor_id", "partner_actor_id", "store_id", "membership_id", "from_state", "to_state", "expected_version", "result_version", "request_hash", "created_at"}, constraints: []string{"store_captain_membership_audit_pkey", "store_captain_membership_audit_idempotency_key_key", "store_captain_membership_audit_event_chk", "store_captain_membership_audit_correlation_chk", "store_captain_membership_audit_state_chk", "store_captain_membership_audit_version_chk", "store_captain_membership_audit_hash_chk", "store_captain_membership_audit_store_partner_fk", "store_captain_membership_audit_membership_fk", "store_captain_membership_audit_idempotency_fk"}, indexes: []string{"store_captain_membership_audit_store_idx"}},
}

func Open(databaseURL string) (*sql.DB, error) {
	databaseURL = strings.TrimSpace(databaseURL)
	if databaseURL == "" {
		return nil, errors.New("DSH_DATABASE_URL is required")
	}
	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open DSH database: %w", err)
	}
	db.SetMaxOpenConns(20)
	db.SetMaxIdleConns(10)
	db.SetConnMaxLifetime(30 * time.Minute)
	return db, nil
}

func LoadMigrations(directory string) ([]MigrationRecord, []string, error) {
	if strings.TrimSpace(directory) == "" {
		return nil, nil, errors.New("DSH_MIGRATION_DIR is required")
	}
	names := []string{"001_partner_store_baseline.sql", "002_store_publication.sql", "003_joining_cases_and_catalog.sql", "004_central_product_store_assortment_cutover.sql", "005_joining_case_partner_correction.sql", "006_joining_case_correct_and_resubmit.sql", "007_location_core.sql", "008_location_core_corrective_boundaries.sql", "009_service_city_scope.sql", "010_central_catalog_refoundation.sql", "011_cart_checkout_order.sql", "012_catalog_semantic_correction.sql", "013_catalog_variant_mutations.sql", "014_catalog_proposal_import_closure.sql", "015_captain_dispatch_and_identity_boundary.sql", "016_captain_phone_constraint_correction.sql", "017_captain_access_and_timeout_canonicalization.sql", "018_remove_unjustified_captain_terminated_state.sql", "019_captain_delivery_recovery.sql", "020_field_standing_admission_and_joining_scope.sql", "021_joining_case_store_origin.sql", "022_order_payment_intents.sql", "023_catalog_media_management.sql", "024_catalog_media_assets.sql", "025_order_client_cancellation.sql", "026_captain_live_location.sql", "027_notification_read_state.sql", "028_client_favorite_stores.sql", "029_order_delivery_proof.sql", "030_order_ratings.sql", "031_field_joining_writer_cutover.sql", "032_catalog_quantity_inventory.sql", "033_partner_financial_terms_binding.sql", "034_field_commission_publication_outbox.sql", "035_order_fulfillment_mode.sql", "036_commerce_financial_handoff_outbox.sql", "037_financial_handoff_actor_provenance.sql", "038_order_conversation.sql", "039_promotions_discovery_content.sql", "040_multi_store_checkout.sql", "041_store_profile_media.sql", "042_field_notifications.sql", "043_discovery_content_analytics.sql", "044_store_pickup_financial_handoff.sql", "045_customer_pickup_fulfillment.sql", "046_store_fulfillment_modes_management.sql", "047_store_captain_membership.sql", "048_customer_pickup_cash_at_store_payment.sql", "049_customer_pickup_order_audit_events.sql", "050_delivery_proof_encryption.sql", "051_store_captain_dispatch_offers.sql", "052_partner_captain_fulfillment_mode.sql", "053_operator_store_fulfillment_modes.sql", "054_partner_captain_store_cash_handoff.sql", "055_catalog_registry_change_audit.sql", "056_catalog_attribute_rule_change_control.sql", "057_catalog_proposal_attribute_values.sql", "058_captain_operator_availability_reason.sql", "059_commerce_vertical_catalog_model.sql", "060_catalog_product_description.sql"}
	records := make([]MigrationRecord, 0, len(names))
	sqls := make([]string, 0, len(names))
	for version, name := range names {
		raw, err := os.ReadFile(filepath.Join(directory, name))
		if err != nil {
			return nil, nil, fmt.Errorf("read DSH migration %s: %w", name, err)
		}
		if len(raw) == 0 {
			return nil, nil, fmt.Errorf("DSH migration %s is empty", name)
		}
		digest := sha256.Sum256(raw)
		records = append(records, MigrationRecord{Version: version + 1, Name: name, SHA256: hex.EncodeToString(digest[:])})
		sqls = append(sqls, string(raw))
	}
	return records, sqls, nil
}

func Migrate(ctx context.Context, db *sql.DB, records []MigrationRecord, migrationSQL []string, proofKeys *DeliveryProofKeyring) error {
	if db == nil || len(records) != SchemaVersion || len(migrationSQL) != len(records) {
		return errors.New("invalid DSH migration input")
	}
	if proofKeys == nil {
		return errors.New("DSH delivery proof keyring is required for schema migration")
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("DSH migration transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, "SELECT pg_advisory_xact_lock(hashtextextended('dsh:migrations', 0))"); err != nil {
		return fmt.Errorf("DSH migration advisory lock: %w", err)
	}
	if _, err := tx.ExecContext(ctx, "CREATE SCHEMA IF NOT EXISTS dsh"); err != nil {
		return fmt.Errorf("create DSH schema: %w", err)
	}
	if _, err := tx.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS dsh.schema_migrations (version integer PRIMARY KEY, name text NOT NULL, sha256 text NOT NULL, applied_at timestamptz NOT NULL DEFAULT clock_timestamp())`); err != nil {
		return fmt.Errorf("create DSH migration history: %w", err)
	}
	var current int
	if err := tx.QueryRowContext(ctx, "SELECT COALESCE(MAX(version), 0) FROM dsh.schema_migrations").Scan(&current); err != nil {
		return fmt.Errorf("read DSH migration history: %w", err)
	}
	if current > SchemaVersion {
		return fmt.Errorf("DSH schema is newer than this binary: %d", current)
	}
	for _, record := range records {
		if record.Version > current {
			break
		}
		var name, digest string
		if err := tx.QueryRowContext(ctx, "SELECT name, sha256 FROM dsh.schema_migrations WHERE version=$1", record.Version).Scan(&name, &digest); err != nil {
			return fmt.Errorf("read DSH migration v%d: %w", record.Version, err)
		}
		if name != record.Name || digest != record.SHA256 {
			return fmt.Errorf("DSH migration checksum mismatch at v%d", record.Version)
		}
	}
	for index := current; index < SchemaVersion; index++ {
		record := records[index]
		if record.Version != current+1 {
			return fmt.Errorf("DSH migration v%d cannot follow schema v%d", record.Version, current)
		}
		if _, err := tx.ExecContext(ctx, migrationSQL[index]); err != nil {
			return fmt.Errorf("apply DSH canonical migration v%d: %w", record.Version, err)
		}
		if _, err := tx.ExecContext(ctx, "INSERT INTO dsh.schema_migrations(version, name, sha256) VALUES($1,$2,$3)", record.Version, record.Name, record.SHA256); err != nil {
			return fmt.Errorf("record DSH migration v%d: %w", record.Version, err)
		}
		current++
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit DSH migrations through v%d: %w", SchemaVersion, err)
	}
	if err := MigrateDeliveryProofCryptography(ctx, db, proofKeys); err != nil {
		return fmt.Errorf("migrate DSH delivery proof material: %w", err)
	}
	return nil
}

func VerifySchema(ctx context.Context, db *sql.DB, records []MigrationRecord) error {
	if db == nil {
		return errors.New("DSH database is nil")
	}
	if len(records) != SchemaVersion {
		return errors.New("invalid DSH migration records")
	}
	if err := db.PingContext(ctx); err != nil {
		return fmt.Errorf("DSH database ping: %w", err)
	}
	var count int
	if err := db.QueryRowContext(ctx, "SELECT COUNT(*) FROM dsh.schema_migrations").Scan(&count); err != nil {
		return fmt.Errorf("DSH migration history count: %w", err)
	}
	if count != len(records) {
		return fmt.Errorf("DSH migration history count mismatch: got %d want %d", count, len(records))
	}
	for _, record := range records {
		var version int
		var name, digest string
		if err := db.QueryRowContext(ctx, "SELECT version, name, sha256 FROM dsh.schema_migrations WHERE version=$1", record.Version).Scan(&version, &name, &digest); err != nil {
			return fmt.Errorf("DSH migration readback v%d: %w", record.Version, err)
		}
		if version != record.Version || name != record.Name || digest != record.SHA256 {
			return fmt.Errorf("DSH migration history does not match canonical v%d", record.Version)
		}
	}
	for _, table := range requiredTables {
		var exists bool
		if err := db.QueryRowContext(ctx, "SELECT to_regclass($1) IS NOT NULL", table.name).Scan(&exists); err != nil {
			return fmt.Errorf("DSH relation check %s: %w", table.name, err)
		}
		if !exists {
			return fmt.Errorf("DSH required relation missing: %s", table.name)
		}
		parts := strings.SplitN(table.name, ".", 2)
		rows, err := db.QueryContext(ctx, "SELECT column_name FROM information_schema.columns WHERE table_schema=$1 AND table_name=$2", parts[0], parts[1])
		if err != nil {
			return fmt.Errorf("DSH columns %s: %w", table.name, err)
		}
		found := map[string]bool{}
		for rows.Next() {
			var column string
			if err := rows.Scan(&column); err != nil {
				_ = rows.Close()
				return fmt.Errorf("DSH column scan %s: %w", table.name, err)
			}
			found[column] = true
		}
		if err := rows.Err(); err != nil {
			_ = rows.Close()
			return fmt.Errorf("DSH column rows %s: %w", table.name, err)
		}
		if err := rows.Close(); err != nil {
			return fmt.Errorf("DSH column close %s: %w", table.name, err)
		}
		for _, column := range table.columns {
			if !found[column] {
				return fmt.Errorf("DSH required column missing: %s.%s", table.name, column)
			}
		}
		for _, column := range table.forbiddenColumns {
			if found[column] {
				return fmt.Errorf("DSH forbidden legacy column remains: %s.%s", table.name, column)
			}
		}
		for _, constraint := range table.constraints {
			var present bool
			if err := db.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=$1::regclass AND conname=$2)", table.name, constraint).Scan(&present); err != nil {
				return fmt.Errorf("DSH constraint check %s.%s: %w", table.name, constraint, err)
			}
			if !present {
				return fmt.Errorf("DSH required constraint missing: %s.%s", table.name, constraint)
			}
		}
		for _, index := range table.indexes {
			var present bool
			if err := db.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname=$1 AND tablename=$2 AND indexname=$3)", parts[0], parts[1], index).Scan(&present); err != nil {
				return fmt.Errorf("DSH index check %s.%s: %w", table.name, index, err)
			}
			if !present {
				return fmt.Errorf("DSH required index missing: %s.%s", table.name, index)
			}
		}
	}
	var databaseNow time.Time
	if err := db.QueryRowContext(ctx, "SELECT clock_timestamp()").Scan(&databaseNow); err != nil {
		return fmt.Errorf("DSH database clock: %w", err)
	}
	drift := time.Since(databaseNow)
	if drift < 0 {
		drift = -drift
	}
	if drift > 30*time.Second {
		return fmt.Errorf("DSH database clock drift exceeds 30s: %s", drift)
	}
	return nil
}

func VerifyDeliveryProofKeyring(ctx context.Context, db *sql.DB, keys *DeliveryProofKeyring) error {
	if db == nil || keys == nil {
		return errors.New("DSH delivery proof keyring is unavailable")
	}
	rows, err := db.QueryContext(ctx, `SELECT code_key_id FROM dsh.commerce_order_delivery_proofs WHERE state='PENDING'
		UNION SELECT split_part(request_hash,'.',2) FROM dsh.commerce_order_transition_idempotency WHERE request_hash LIKE 'v1.%'
		UNION SELECT split_part(request_hash,'.',2) FROM dsh.captain_operation_idempotency WHERE operation='complete' AND request_hash LIKE 'v1.%'`)
	if err != nil {
		return fmt.Errorf("read DSH delivery proof key references: %w", err)
	}
	defer func() { _ = rows.Close() }()
	for rows.Next() {
		var keyID string
		if err := rows.Scan(&keyID); err != nil {
			return fmt.Errorf("scan DSH delivery proof key reference: %w", err)
		}
		if !keys.HasKey(keyID) {
			return fmt.Errorf("DSH delivery proof keyring is missing referenced key %q", keyID)
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("read DSH delivery proof key references: %w", err)
	}
	return nil
}
