import { useAppearanceTheme } from "@bthwani/design-system/native";
import { AuthenticatedMobileBoundary } from "@bthwani/identity/presentation";
import { type Href, Tabs, usePathname, useRouter } from "expo-router";
import { useCallback, useMemo } from "react";
import { currentIdentityState, restoreIdentitySession, subscribeIdentitySession } from "../../src/bootstrap/identity";
import { createCaptainTabOptions } from "../../src/shell/captain-shell";

const identity = { restoreIdentitySession, currentIdentityState, subscribe: subscribeIdentitySession };
export default function CaptainAppLayout() { const router = useRouter(); const pathname = usePathname(); const theme = useAppearanceTheme(); const tabOptions = useMemo(() => createCaptainTabOptions(theme), [theme]); const onUnauthenticated = useCallback(() => router.replace(pathname === "/" ? "/" : `/?returnTo=${encodeURIComponent(pathname)}` as Href), [pathname, router]); return <AuthenticatedMobileBoundary binding={identity} onUnauthenticated={onUnauthenticated}><Tabs screenOptions={tabOptions} screenListeners={({ route }) => ({ tabPress: (event) => { const path = route.name === "home" ? "/(app)/home" : route.name === "offers" ? "/(app)/offers" : route.name === "deliveries" ? "/(app)/deliveries" : route.name === "wallet" ? "/(app)/wallet" : route.name === "account" ? "/(app)/account" : null; if (!path) return; event.preventDefault(); router.replace(path as Href); } })}><Tabs.Screen name="home" options={{ title: "الرئيسية", tabBarAccessibilityLabel: "جاهزية الكابتن" }} /><Tabs.Screen name="offers" options={{ title: "العروض", tabBarAccessibilityLabel: "عروض التوصيل" }} /><Tabs.Screen name="deliveries" options={{ title: "التوصيلات", tabBarAccessibilityLabel: "التوصيلات الحالية" }} /><Tabs.Screen name="wallet" options={{ title: "المحفظة", tabBarAccessibilityLabel: "محفظة الكابتن" }} /><Tabs.Screen name="account" options={{ title: "الحساب", tabBarAccessibilityLabel: "حساب الكابتن" }} /></Tabs></AuthenticatedMobileBoundary>; }
