CREATE TABLE dsh.store_operational_availability (
    store_id text PRIMARY KEY REFERENCES dsh.stores(id) ON DELETE CASCADE,
    schedule_mode text NOT NULL DEFAULT 'ALWAYS_OPEN',
    weekly_schedule jsonb NOT NULL DEFAULT '[]'::jsonb,
    paused boolean NOT NULL DEFAULT false,
    pause_reason text,
    pause_until timestamptz,
    preparation_minutes integer,
    unavailable_fulfillment_modes text[] NOT NULL DEFAULT ARRAY[]::text[],
    version integer NOT NULL DEFAULT 1,
    updated_by_actor_id text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_operational_availability_schedule_mode_chk
        CHECK (schedule_mode IN ('ALWAYS_OPEN','WEEKLY')),
    CONSTRAINT store_operational_availability_schedule_chk
        CHECK (
            (schedule_mode = 'ALWAYS_OPEN' AND weekly_schedule = '[]'::jsonb)
            OR (schedule_mode = 'WEEKLY' AND jsonb_typeof(weekly_schedule) = 'array')
        ),
    CONSTRAINT store_operational_availability_pause_chk
        CHECK (
            (paused = false AND pause_reason IS NULL AND pause_until IS NULL)
            OR (paused = true AND pause_reason IS NOT NULL AND length(btrim(pause_reason)) BETWEEN 2 AND 500)
        ),
    CONSTRAINT store_operational_availability_preparation_chk
        CHECK (preparation_minutes IS NULL OR preparation_minutes BETWEEN 1 AND 1440),
    CONSTRAINT store_operational_availability_modes_chk
        CHECK (unavailable_fulfillment_modes <@ ARRAY['BTHWANI_CAPTAIN','PARTNER_CAPTAIN','CUSTOMER_PICKUP']::text[]),
    CONSTRAINT store_operational_availability_modes_unique_chk
        CHECK (cardinality(unavailable_fulfillment_modes) = cardinality(ARRAY(SELECT DISTINCT unnest(unavailable_fulfillment_modes)))),
    CONSTRAINT store_operational_availability_version_chk CHECK (version > 0),
    CONSTRAINT store_operational_availability_actor_chk CHECK (length(btrim(updated_by_actor_id)) BETWEEN 1 AND 128)
);

INSERT INTO dsh.store_operational_availability(store_id, schedule_mode, weekly_schedule, paused, unavailable_fulfillment_modes, version, updated_by_actor_id)
SELECT id, 'ALWAYS_OPEN', '[]'::jsonb, false, ARRAY[]::text[], 1, 'system:migration:085'
FROM dsh.stores
ON CONFLICT(store_id) DO NOTHING;

CREATE TABLE dsh.store_operational_availability_idempotency (
    idempotency_key text PRIMARY KEY,
    request_hash text NOT NULL,
    store_id text NOT NULL REFERENCES dsh.stores(id) ON DELETE CASCADE,
    acting_actor_id text NOT NULL,
    result_version integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_operational_availability_idem_key_chk CHECK (length(btrim(idempotency_key)) BETWEEN 8 AND 128),
    CONSTRAINT store_operational_availability_idem_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_operational_availability_idem_actor_chk CHECK (length(btrim(acting_actor_id)) BETWEEN 1 AND 128),
    CONSTRAINT store_operational_availability_idem_version_chk CHECK (result_version > 0)
);

CREATE TABLE dsh.store_operational_availability_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id text NOT NULL REFERENCES dsh.stores(id) ON DELETE RESTRICT,
    event_type text NOT NULL,
    idempotency_key text NOT NULL UNIQUE REFERENCES dsh.store_operational_availability_idempotency(idempotency_key) ON DELETE RESTRICT,
    correlation_id text NOT NULL,
    acting_actor_id text NOT NULL,
    authority_source text NOT NULL,
    expected_version integer NOT NULL,
    result_version integer NOT NULL,
    request_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_operational_availability_audit_event_chk CHECK (event_type = 'operational_availability_changed'),
    CONSTRAINT store_operational_availability_audit_correlation_chk CHECK (length(btrim(correlation_id)) BETWEEN 8 AND 128),
    CONSTRAINT store_operational_availability_audit_actor_chk CHECK (length(btrim(acting_actor_id)) BETWEEN 1 AND 128),
    CONSTRAINT store_operational_availability_audit_authority_chk CHECK (authority_source IN ('STORE_OWNER','STORE_GRANT','OPERATOR')),
    CONSTRAINT store_operational_availability_audit_version_chk CHECK (expected_version > 0 AND result_version = expected_version + 1),
    CONSTRAINT store_operational_availability_audit_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$')
);

CREATE INDEX store_operational_availability_updated_idx
    ON dsh.store_operational_availability(updated_at DESC, store_id);
