CREATE TABLE dsh.store_access_grants (
    id text PRIMARY KEY,
    store_id text NOT NULL,
    owner_partner_actor_id text NOT NULL,
    delegate_actor_id text NOT NULL,
    permissions text[] NOT NULL,
    state text NOT NULL,
    version integer NOT NULL DEFAULT 1,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    declined_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_access_grants_id_chk CHECK (length(btrim(id)) BETWEEN 1 AND 128),
    CONSTRAINT store_access_grants_owner_delegate_chk CHECK (btrim(owner_partner_actor_id) <> '' AND btrim(delegate_actor_id) <> '' AND owner_partner_actor_id <> delegate_actor_id),
    CONSTRAINT store_access_grants_permissions_chk CHECK (
        cardinality(permissions) BETWEEN 1 AND 3
        AND permissions <@ ARRAY['orders','catalog','store_operations']::text[]
    ),
    CONSTRAINT store_access_grants_state_chk CHECK (state IN ('pending_role_admission','pending_acceptance','active','suspended','revoked','declined','expired')),
    CONSTRAINT store_access_grants_version_chk CHECK (version > 0),
    CONSTRAINT store_access_grants_time_chk CHECK (expires_at > created_at),
    CONSTRAINT store_access_grants_state_facts_chk CHECK (
        (state IN ('pending_role_admission','pending_acceptance') AND accepted_at IS NULL AND declined_at IS NULL AND revoked_at IS NULL)
        OR (state IN ('active','suspended') AND accepted_at IS NOT NULL AND declined_at IS NULL AND revoked_at IS NULL)
        OR (state = 'revoked' AND revoked_at IS NOT NULL AND declined_at IS NULL)
        OR (state = 'declined' AND declined_at IS NOT NULL AND accepted_at IS NULL AND revoked_at IS NULL)
        OR (state = 'expired' AND revoked_at IS NULL AND declined_at IS NULL)
    ),
    CONSTRAINT store_access_grants_store_owner_fk
        FOREIGN KEY (store_id, owner_partner_actor_id)
        REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX store_access_grants_current_delegate_uq
    ON dsh.store_access_grants(store_id, delegate_actor_id)
    WHERE state IN ('pending_role_admission','pending_acceptance','active','suspended');

CREATE INDEX store_access_grants_owner_idx
    ON dsh.store_access_grants(owner_partner_actor_id, store_id, created_at DESC);

CREATE INDEX store_access_grants_delegate_idx
    ON dsh.store_access_grants(delegate_actor_id, created_at DESC, id);

CREATE TABLE dsh.store_access_grant_idempotency (
    idempotency_key text PRIMARY KEY,
    request_hash text NOT NULL,
    operation text NOT NULL,
    grant_id text NOT NULL REFERENCES dsh.store_access_grants(id) ON DELETE RESTRICT,
    acting_actor_id text NOT NULL,
    result_state text NOT NULL,
    result_version integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_access_grant_idem_key_chk CHECK (length(btrim(idempotency_key)) BETWEEN 8 AND 128),
    CONSTRAINT store_access_grant_idem_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_access_grant_idem_operation_chk CHECK (operation IN ('invitation_create','role_admission_confirm','invitation_accept','invitation_decline','grant_transition')),
    CONSTRAINT store_access_grant_idem_state_chk CHECK (result_state IN ('pending_role_admission','pending_acceptance','active','suspended','revoked','declined','expired')),
    CONSTRAINT store_access_grant_idem_version_chk CHECK (result_version > 0)
);

CREATE TABLE dsh.store_access_grant_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    idempotency_key text NOT NULL UNIQUE REFERENCES dsh.store_access_grant_idempotency(idempotency_key) ON DELETE RESTRICT,
    correlation_id text NOT NULL,
    acting_actor_id text NOT NULL,
    owner_partner_actor_id text NOT NULL,
    delegate_actor_id text NOT NULL,
    store_id text NOT NULL,
    grant_id text NOT NULL REFERENCES dsh.store_access_grants(id) ON DELETE RESTRICT,
    from_state text,
    to_state text NOT NULL,
    expected_version integer NOT NULL,
    result_version integer NOT NULL,
    request_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT store_access_grant_audit_event_chk CHECK (event_type IN ('invitation_created','role_admission_confirmed','invitation_accepted','invitation_declined','grant_state_changed')),
    CONSTRAINT store_access_grant_audit_correlation_chk CHECK (length(btrim(correlation_id)) BETWEEN 8 AND 128),
    CONSTRAINT store_access_grant_audit_state_chk CHECK (
        to_state IN ('pending_role_admission','pending_acceptance','active','suspended','revoked','declined','expired')
        AND (from_state IS NULL OR from_state IN ('pending_role_admission','pending_acceptance','active','suspended','revoked','declined','expired'))
    ),
    CONSTRAINT store_access_grant_audit_version_chk CHECK (expected_version >= 0 AND result_version >= expected_version AND result_version <= expected_version + 1),
    CONSTRAINT store_access_grant_audit_hash_chk CHECK (request_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT store_access_grant_audit_store_owner_fk
        FOREIGN KEY (store_id, owner_partner_actor_id) REFERENCES dsh.stores(id, partner_actor_id) ON DELETE RESTRICT
);

CREATE INDEX store_access_grant_audit_store_idx
    ON dsh.store_access_grant_audit(store_id, created_at DESC);
